/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_DRIVERTYPE_H
#define RTF_MAINTAIND_IMPL_TYPE_DRIVERTYPE_H

#include "rtf/stdtype/impl_type_uint16_t.h"
namespace rtf {
namespace maintaind {
enum class DriverType : rtf::stdtype::uint16_t {
    DDS,
    SOMEIP
};
}
}

#endif // RTF_MAINTAIND_IMPL_TYPE_DRIVERTYPE_H
