/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_VECTORNODEINFO_H
#define RTF_MAINTAIND_IMPL_TYPE_VECTORNODEINFO_H
#include "ara/core/vector.h"
#include "rtf/maintaind/impl_type_nodeinfo.h"

namespace rtf {
namespace maintaind {
using VectorNodeInfo = ara::core::Vector<rtf::maintaind::NodeInfo>;
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_VECTORNODEINFO_H
