/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_EVENTMAP_H
#define RTF_MAINTAIND_IMPL_TYPE_EVENTMAP_H
#include "ara/core/map.h"
#include "rtf/maintaind/impl_type_eventinfo.h"
#include "rtf/maintaind/impl_type_drivertype.h"

namespace rtf {
namespace maintaind {
using EventMap = ara::core::Map<rtf::maintaind::DriverType, rtf::maintaind::EventInfo>;
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_EVENTMAP_H
