/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_STRUCTSERIALIZATIONPOLICY_H
#define RTF_MAINTAIND_IMPL_TYPE_STRUCTSERIALIZATIONPOLICY_H

#include "rtf/stdtype/impl_type_uint8_t.h"
namespace rtf {
namespace maintaind {
enum class StructSerializationPolicy : rtf::stdtype::uint8_t {
    OUT_LAYER_ALIGNMENT,
    DISABLE_OUT_LAYER_ALIGNMENT
};
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_STRUCTSERIALIZATIONPOLICY_H
