/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_VECTORERRORDOMAIN_H
#define RTF_MAINTAIND_IMPL_TYPE_VECTORERRORDOMAIN_H
#include "ara/core/vector.h"
#include "rtf/maintaind/impl_type_errordomaininfo.h"

namespace rtf {
namespace maintaind {
using VectorErrorDomain = ara::core::Vector<rtf::maintaind::ErrorDomainInfo>;
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_VECTORERRORDOMAIN_H
