/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_ERRORDOMAININFO_H
#define RTF_MAINTAIND_IMPL_TYPE_ERRORDOMAININFO_H
#include "rtf/stdtype/impl_type_uint64_t.h"
#include "rtf/stdtype/impl_type_string.h"

namespace rtf {
namespace maintaind {
struct ErrorDomainInfo {
    ::rtf::stdtype::uint64_t id_;
    ::rtf::stdtype::String name_;

    static bool IsPlane() noexcept
    {
        return false;
    }

    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun) noexcept
    {
        fun(id_);
        fun(name_);
    }

    template<typename F>
    void enumerate(F& fun) const noexcept
    {
        fun(id_);
        fun(name_);
    }

    bool operator == (const ::rtf::maintaind::ErrorDomainInfo& t) const noexcept
    {
        return (id_ == t.id_) && (name_ == t.name_);
    }
};
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_ERRORDOMAININFO_H
