/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_QUERYMETHODINFORETURNTYPE_H
#define RTF_MAINTAIND_IMPL_TYPE_QUERYMETHODINFORETURNTYPE_H
#include "ara/core/vector.h"
#include "rtf/maintaind/impl_type_methodregisterinfo.h"

namespace rtf {
namespace maintaind {
using QueryMethodInfoReturnType = ara::core::Vector<rtf::maintaind::MethodRegisterInfo>;
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_QUERYMETHODINFORETURNTYPE_H
