/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_REGISTERINFOTYPE_H
#define RTF_MAINTAIND_IMPL_TYPE_REGISTERINFOTYPE_H

#include "rtf/stdtype/impl_type_uint16_t.h"
namespace rtf {
namespace maintaind {
enum class RegisterInfoType : rtf::stdtype::uint16_t {
    NODE_PID_INFO,
    NODE_E2E_INFO
};
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_REGISTERINFOTYPE_H
