/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_SOMEIPEVENTINFO_H
#define RTF_MAINTAIND_IMPL_TYPE_SOMEIPEVENTINFO_H
#include "rtf/stdtype/impl_type_boolean.h"
#include "rtf/stdtype/impl_type_string.h"
#include "rtf/basetype/impl_type_vectoruint16.h"
#include "rtf/stdtype/impl_type_uint32_t.h"
#include "rtf/stdtype/impl_type_uint16_t.h"
#include "rtf/maintaind/e2e/impl_type_e2econfiginfo.h"
#include "rtf/maintaind/serialize/impl_type_serializeconfigrawdata.h"
#include "rtf/maintaind/pdu/impl_type_pduconfig.h"
namespace rtf {
namespace maintaind {
struct SomeipEventInfo {
    ::rtf::stdtype::uint16_t serviceId_;
    ::rtf::stdtype::uint16_t instanceId_;
    ::rtf::stdtype::uint32_t entityId_;
    ::rtf::stdtype::uint16_t eventId_;
    ::rtf::basetype::VectorUint16 eventGroupId_;
    ::rtf::stdtype::String instanceShortName_;
    ::rtf::stdtype::uint16_t portNumber_;
    ::rtf::stdtype::uint32_t minorVersion_;
    ::rtf::stdtype::uint16_t majorVersion_;
    ::rtf::stdtype::boolean isReliable_;
    ::rtf::maintaind::E2EConfigInfo e2eConfig_;
    ::rtf::maintaind::SerializeConfigRawData serializeConfig_;
    ::rtf::maintaind::PduConfigInfo pduConfig_;
    static bool IsPlane() noexcept
    {
        return false;
    }

    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun) noexcept
    {
        fun(serviceId_);
        fun(instanceId_);
        fun(entityId_);
        fun(eventId_);
        fun(eventGroupId_);
        fun(instanceShortName_);
        fun(portNumber_);
        fun(minorVersion_);
        fun(majorVersion_);
        fun(isReliable_);
        fun(e2eConfig_);
        fun(serializeConfig_);
        fun(pduConfig_);
    }

    bool operator == (const ::rtf::maintaind::SomeipEventInfo& t) const noexcept
    {
        return (serviceId_ == t.serviceId_) && (instanceId_ == t.instanceId_) && (entityId_ == t.entityId_) &&
        (eventId_ == t.eventId_) && (eventGroupId_ == t.eventGroupId_) &&
        (instanceShortName_ == t.instanceShortName_) && (portNumber_ == t.portNumber_) &&
        (minorVersion_ == t.minorVersion_) && (majorVersion_ == t.majorVersion_) && (isReliable_ == t.isReliable_) &&
        (e2eConfig_ == t.e2eConfig_) && (serializeConfig_ == t.serializeConfig_) && (pduConfig_ == t.pduConfig_);
    }
};
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_SOMEIPEVENTINFO_H
