/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_METHODMAP_H
#define RTF_MAINTAIND_IMPL_TYPE_METHODMAP_H
#include "ara/core/map.h"
#include "rtf/maintaind/impl_type_drivertype.h"
#include "rtf/maintaind/impl_type_methodinfo.h"

namespace rtf {
namespace maintaind {
using MethodMap = ara::core::Map<rtf::maintaind::DriverType, rtf::maintaind::MethodInfo>;
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_METHODMAP_H
