/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_SERIALIZATIONTYPE_H
#define RTF_MAINTAIND_IMPL_TYPE_SERIALIZATIONTYPE_H

#include "rtf/stdtype/impl_type_uint32_t.h"
namespace rtf {
namespace maintaind {
enum class SerializationType : rtf::stdtype::uint32_t {
    ROS,
    CM,
    SIGNAL_BASED,
    CM_SOMEIP_SERIALIZE_CONFIG
};
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_SERIALIZATIONTYPE_H
