/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_RETURNCODE_H
#define RTF_MAINTAIND_IMPL_TYPE_RETURNCODE_H

#include "rtf/stdtype/impl_type_uint16_t.h"
namespace rtf {
namespace maintaind {
enum class ReturnCode : rtf::stdtype::uint16_t {
    OK,
    ERROR
};
}
}

#endif // RTF_MAINTAIND_IMPL_TYPE_RETURNCODE_H
