/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2020. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_RTFMAINTAINDTOOLSSERVICE_SKELETON_COMMON_H
#define RTF_MAINTAIND_RTFMAINTAINDTOOLSSERVICE_SKELETON_COMMON_H

#include "ara/com/internal/skeleton/skeleton_adapter.h"
#include "ara/com/internal/skeleton/event_adapter.h"
#include "ara/com/internal/skeleton/field_adapter.h"
#include "ara/com/internal/skeleton/method_adapter.h"
#include "rtf/maintaind/rtfmaintaindtoolsservice_common.h"
#include <cstdint>

namespace rtf {
namespace maintaind {
namespace skeleton {
namespace events {
}

namespace methods {
    using QueryAllDataTypeHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using QueryDataTypeHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using QueryDataTypeRefListHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using QueryEventInfoHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using QueryEventShowHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using QueryLatencyResultHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using QueryLatencyStatusHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using QueryMethodInfoHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using QueryMethodTypeHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using QueryNodeInfoHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using QuerySubNodeEventInfoHandle = ara::com::internal::skeleton::method::MethodAdapter;
    using SwitchLatencyModeHandle = ara::com::internal::skeleton::method::MethodAdapter;
    static constexpr ara::com::internal::EntityId QueryAllDataTypeId = 56963U; // QueryAllDataType_method_hash
    static constexpr ara::com::internal::EntityId QueryDataTypeId = 32777U; // QueryDataType_method_hash
    static constexpr ara::com::internal::EntityId QueryDataTypeRefListId = 60394U; // QueryDataTypeRefList_method_hash
    static constexpr ara::com::internal::EntityId QueryEventInfoId = 40538U; // QueryEventInfo_method_hash
    static constexpr ara::com::internal::EntityId QueryEventShowId = 23108U; // QueryEventShow_method_hash
    static constexpr ara::com::internal::EntityId QueryLatencyResultId = 58300U; // QueryLatencyResult_method_hash
    static constexpr ara::com::internal::EntityId QueryLatencyStatusId = 3562U; // QueryLatencyStatus_method_hash
    static constexpr ara::com::internal::EntityId QueryMethodInfoId = 38078U; // QueryMethodInfo_method_hash
    static constexpr ara::com::internal::EntityId QueryMethodTypeId = 12452U; // QueryMethodType_method_hash
    static constexpr ara::com::internal::EntityId QueryNodeInfoId = 47109U; // QueryNodeInfo_method_hash
    static constexpr ara::com::internal::EntityId QuerySubNodeEventInfoId = 7391U; // QuerySubNodeEventInfo_method_hash
    static constexpr ara::com::internal::EntityId SwitchLatencyModeId = 63267U; // SwitchLatencyMode_method_hash
}

namespace fields {
}
} // namespace skeleton
} // namespace maintaind
} // namespace rtf

#endif // RTF_MAINTAIND_RTFMAINTAINDTOOLSSERVICE_SKELETON_COMMON_H
