/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_RTFMAINTAINDTOOLSSERVICE_COMMON_H
#define RTF_MAINTAIND_RTFMAINTAINDTOOLSSERVICE_COMMON_H

#include "ara/com/types.h"
#include "rtf/maintaind/impl_type_datatypemap.h"
#include "rtf/stdtype/impl_type_string.h"
#include "rtf/maintaind/impl_type_datatyperefmap.h"
#include "rtf/maintaind/impl_type_queryeventinforeturntype.h"
#include "rtf/maintaind/latency/impl_type_latencyswitch.h"
#include "rtf/maintaind/latency/impl_type_latencyqueryinfo.h"
#include "rtf/maintaind/latency/impl_type_latencyresult.h"
#include "rtf/maintaind/impl_type_querymethodinforeturntype.h"
#include "rtf/maintaind/impl_type_methoddatatypeinfo.h"
#include "rtf/maintaind/impl_type_vectornodeinfo.h"
#include "rtf/maintaind/impl_type_querysubeventinfoindex.h"
#include "rtf/maintaind/impl_type_eventinfowithpubsub.h"
#include "rtf/maintaind/latency/impl_type_latencyresultmap.h"
#include "rtf/maintaind/latency/impl_type_latencystatus.h"
#include "rtf/maintaind/impl_type_returncode.h"
namespace rtf {
namespace maintaind {
class RTFMaintaindToolsService {
public:
    constexpr RTFMaintaindToolsService() = default;
    ~RTFMaintaindToolsService() = default;
    constexpr static ara::com::ServiceIdentifierType ServiceIdentifier = ara::com::ServiceIdentifierType(
        "/huawei/ap/rtf/RTFMaintaindToolsService");
    constexpr static ara::com::ServiceVersionType ServiceVersion = ara::com::ServiceVersionType("1.1");
};
} // namespace maintaind
} // namespace rtf

#endif // RTF_MAINTAIND_RTFMAINTAINDTOOLSSERVICE_COMMON_H
