{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/NmErrorDefine/UserDataErrType",
  "Namespace": "::ara::nm",
  "Type": "ERROR",
  "ErrorDomainId": 0,
  "ErrorDomainName": "UserDataErrType",
  "ErrorCodes": [
    {
      "Id": 0,
      "Name": "UserDataNetworkHandleInvalid"
    },
    {
      "Id": 1,
      "Name": "UserDataPhysicalChannelMsgGetErr"
    },
    {
      "Id": 2,
      "Name": "UserDataPhysicalChannelMsgSetErr"
    }
  ]
}