/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Crypto-Generator
 */

#ifndef HZ_TSP_PKI_LOCAL_CRYPTO_PROVIDER_H
#define HZ_TSP_PKI_LOCAL_CRYPTO_PROVIDER_H
#include "ara/core/string_view.h"
namespace ara {
namespace crypto {
    static const ara::core::StringView KMSCryptoProviderID = "bdfa408d-3d4f-41ff-a33e-f65b05388078";
    static const ara::core::StringView TSPPKI_ORIGIN = "f4686cc4-9fd7-42b1-b03c-75d3e56b6c37";
    static const ara::core::StringView TSPPKI_UPDATE = "f772b0fa-9f71-485b-a923-29051721eeb7";
} // namespace crypto
} // namespace ara
#endif // HZ_TSP_PKI_LOCAL_CRYPTO_PROVIDER_H
