/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_BASETYPE_IMPL_TYPE_VECTORUINT32_H
#define RTF_BASETYPE_IMPL_TYPE_VECTORUINT32_H
#include "ara/core/vector.h"
#include "rtf/stdtype/impl_type_uint32_t.h"

namespace rtf {
namespace basetype {
using VectorUint32 = ara::core::Vector<rtf::stdtype::uint32_t>;
} // namespace basetype
} // namespace rtf


#endif // RTF_BASETYPE_IMPL_TYPE_VECTORUINT32_H
