/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_BASETYPE_IMPL_TYPE_VECTORUINT16_H
#define RTF_BASETYPE_IMPL_TYPE_VECTORUINT16_H
#include "ara/core/vector.h"
#include "rtf/stdtype/impl_type_uint16_t.h"

namespace rtf {
namespace basetype {
using VectorUint16 = ara::core::Vector<rtf::stdtype::uint16_t>;
} // namespace basetype
} // namespace rtf


#endif // RTF_BASETYPE_IMPL_TYPE_VECTORUINT16_H
