/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_BASETYPE_IMPL_TYPE_VECTORSTRING_H
#define RTF_BASETYPE_IMPL_TYPE_VECTORSTRING_H
#include "ara/core/vector.h"
#include "rtf/stdtype/impl_type_string.h"

namespace rtf {
namespace basetype {
using VectorString = ara::core::Vector<rtf::stdtype::String>;
} // namespace basetype
} // namespace rtf


#endif // RTF_BASETYPE_IMPL_TYPE_VECTORSTRING_H
