%YAML:1.0

recvInstances:
    - name: chassis
      type: proto_proxy
      topic: /soc/chassis                        # 对应 hozon::soc::Chassis
      domainId: 0
    - name: nnp_state                            # 该状态下，代表高速自动驾驶，不显示红绿灯
      type: proto_proxy
      topic: /soc/mcu2ego                        # 对应 hozon::soc::mcuToego
      domainId: 0
    - name: forbidden_and_limit                  # 限速标记和禁止标记
      type: proto_proxy
      topic: /perception/fsd/detection/tsr_ihbc  # 对应 hozon::perception::Vision2dDetection
      domainId: 0
    - name: traffic_light                        # 红绿灯
      type: proto_proxy
      topic: /mapping/junction_passable          # 对应 hozon::hdmap::JunctionPassble
      domainId: 0

sendInstances:
    - name: output_canfd                         # 输出 tsrtlr 状态，使用 hozon::soc::Apa2Chassis pb对象
      type: proto_skeleton
      topic: /soc/tsrtlr_output_canfd
      domainId: 0
    - name: output_fsmcore                       # 输出状态机框架的状态，使用 hozon::fsm_output::StateOutput pb对象
      type: proto_skeleton
      topic: /soc/fsmcore_output_tsrtlr
      domainId: 0

log:
    name: fsmcore_ihbc
    description: ihbc
    file: /opt/usr/log/soc_log/
    mode: 3
    level: 2
    adf:
        level: 2

trigger:
    - name: perioical           # 这个可以自己取，用于注册 trigger 对应的 process 函数
      type: PERIOD
      period: 20                # 50 Hz
      auxSources:
          - name: chassis       # 要和recvInstances里的name对应
            timeout: 100
          - name: forbidden_and_limit  # 要和recvInstances里的name对应
            timeout: 1000
          - name: traffic_light     # 要和recvInstances里的name对应
            timeout: 1000
          - name: nnp_state
            timeout: 1000

appName: TSR_TLR                   #Node name
description: TSR_TLR Onboard

fsm_rule_path: /app/runtime_service/ihbc_tsr_tlr/conf/FsmTsrTlrConfig.pb.conf  # 状态机配置文件路径
