/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef FISHEYE_PERCEPTION_LOGGING_BEHAVIOR_H
#define FISHEYE_PERCEPTION_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // FISHEYE_PERCEPTION_LOGGING_BEHAVIOR_H
