/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef FM_SEA_LOGGING_BEHAVIOR_H
#define FM_SEA_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // FM_SEA_LOGGING_BEHAVIOR_H
