/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef FUSION_LIDAR_LOGGING_BEHAVIOR_H
#define FUSION_LIDAR_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // FUSION_LIDAR_LOGGING_BEHAVIOR_H
