/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef HTTPTEST_LOGGING_BEHAVIOR_H
#define HTTPTEST_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // HTTPTEST_LOGGING_BEHAVIOR_H
