/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef HZ_FM_AGENT_LOGGING_BEHAVIOR_H
#define HZ_FM_AGENT_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // HZ_FM_AGENT_LOGGING_BEHAVIOR_H
