/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef HZ_RADARFRONT_LOGGING_BEHAVIOR_H
#define HZ_RADARFRONT_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // HZ_RADARFRONT_LOGGING_BEHAVIOR_H
