/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef LIDAR_TRACK_EXECUTE_LOGGING_BEHAVIOR_H
#define LIDAR_TRACK_EXECUTE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // LIDAR_TRACK_EXECUTE_LOGGING_BEHAVIOR_H
