/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef LOC_LOGGING_BEHAVIOR_H
#define LOC_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // LOC_LOGGING_BEHAVIOR_H
