/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef MAPMVIZEXECUTABLE_LOGGING_BEHAVIOR_H
#define MAPMVIZEXECUTABLE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // MAPMVIZEXECUTABLE_LOGGING_BEHAVIOR_H
