/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef MAPPING_EXECUTE_LOGGING_BEHAVIOR_H
#define MAPPING_EXECUTE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // MAPPING_EXECUTE_LOGGING_BEHAVIOR_H
