/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef NAVIGATION_EXECUTE_LOGGING_BEHAVIOR_H
#define NAVIGATION_EXECUTE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // NAVIGATION_EXECUTE_LOGGING_BEHAVIOR_H
