/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef ODOMETRYEXECUTABLE_LOGGING_BEHAVIOR_H
#define ODOMETRYEXECUTABLE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // ODOMETRYEXECUTABLE_LOGGING_BEHAVIOR_H
