/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef PARKING_FUSION_LOGGING_BEHAVIOR_H
#define PARKING_FUSION_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // PARKING_FUSION_LOGGING_BEHAVIOR_H
