/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef PERCEPTION_LOGGING_BEHAVIOR_H
#define PERCEPTION_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // PERCEPTION_LOGGING_BEHAVIOR_H
