/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef PLANNING_EXECUTE_LOGGING_BEHAVIOR_H
#define PLANNING_EXECUTE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // PLANNING_EXECUTE_LOGGING_BEHAVIOR_H
