/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef ROAD_FEATURE_EXECUTE_LOGGING_BEHAVIOR_H
#define ROAD_FEATURE_EXECUTE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // ROAD_FEATURE_EXECUTE_LOGGING_BEHAVIOR_H
