/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef SAMMANALYSISEXECUTABLE_LOGGING_BEHAVIOR_H
#define SAMMANALYSISEXECUTABLE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // SAMMANALYSISEXECUTABLE_LOGGING_BEHAVIOR_H
