/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef SCENE_MANAGE_EXECUTE_LOGGING_BEHAVIOR_H
#define SCENE_MANAGE_EXECUTE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // SCENE_MANAGE_EXECUTE_LOGGING_BEHAVIOR_H
