/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef SOTIF_PERCEPTION_SAFETY_EXECUTE_LOGGING_BEHAVIOR_H
#define SOTIF_PERCEPTION_SAFETY_EXECUTE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // SOTIF_PERCEPTION_SAFETY_EXECUTE_LOGGING_BEHAVIOR_H
