/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef TRAFFIC_LIGHT_DET_EXECUTE_LOGGING_BEHAVIOR_H
#define TRAFFIC_LIGHT_DET_EXECUTE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // TRAFFIC_LIGHT_DET_EXECUTE_LOGGING_BEHAVIOR_H
