{
  "ShortName": "/DataType/StdCppImplDataType/Duc/CheckUpdateConditionRequest",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "requestBase",
      "Type": "/DataType/StdCppImplDataType/Duc/RequestBase"
    },
    {
      "Name": "ecuVerForUpdate",
      "Type": "/DataType/StdCppImplDataType/Duc/AimsEcuList"
    },
    {
      "Name": "ecuVerForRollback",
      "Type": "/DataType/StdCppImplDataType/Duc/AimsEcuList",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}