{
  "ShortName": "/DataType/StdCppImplDataType/di/RollbackRequest",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "requestBase",
      "Type": "/DataType/StdCppImplDataType/di/RequestBase"
    },
    {
      "Name": "aimsRollbackEcu",
      "Type": "/DataType/StdCppImplDataType/di/AimsEcuArr"
    },
    {
      "Name": "retryTimes",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "fingerprint",
      "Type": "/DataType/StdCppImplDataType/di/Uint8Vec"
    }
  ],
  "IsPlane": "false"
}