{
  "ShortName": "/DataType/StdCppImplDataType/Duc/GetInventoryResultResponse",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "responseBase",
      "Type": "/DataType/StdCppImplDataType/Duc/ResponseBase"
    },
    {
      "Name": "state",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "ecuInventories",
      "Type": "/DataType/StdCppImplDataType/Duc/EcuInventoryList"
    }
  ],
  "IsPlane": "false"
}