{
  "ShortName": "/DataType/StdCppImplDataType/di/GetUpdateProgressResponse",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "responseBase",
      "Type": "/DataType/StdCppImplDataType/di/ResponseBase"
    },
    {
      "Name": "stage",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ecuStatuses",
      "Type": "/DataType/StdCppImplDataType/di/EcuUpdateStatusArr"
    }
  ],
  "IsPlane": "false"
}