{
  "ShortName": "/DataType/StdCppImplDataType/di/GetLogCollectionResultResponse",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "responseBase",
      "Type": "/DataType/StdCppImplDataType/di/ResponseBase"
    },
    {
      "Name": "state",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "logPathList",
      "Type": "/DataType/StdCppImplDataType/di/StringArr"
    }
  ],
  "IsPlane": "false"
}