{
  "ShortName": "/DataType/StdCppImplDataType/di/CheckUpdateConditionRequest",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "requestBase",
      "Type": "/DataType/StdCppImplDataType/di/RequestBase"
    },
    {
      "Name": "ecuList",
      "Type": "/DataType/StdCppImplDataType/di/EcuIdentityArr",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}