{
  "ShortName": "/DataType/StdCppImplDataType/di/AimsEcu",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ecuInfo",
      "Type": "/DataType/StdCppImplDataType/di/EcuInfo"
    },
    {
      "Name": "packagePath",
      "Type": "/DataType/StdCppImplDataType/di/string",
      "IsOptional": "false"
    },
    {
      "Name": "softVersion",
      "Type": "/DataType/StdCppImplDataType/di/string"
    },
    {
      "Name": "calibrateVersion",
      "Type": "/DataType/StdCppImplDataType/di/string",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}