{
  "ShortName": "/DataType/StdCppImplDataType/Duc/InstallRequest",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "requestBase",
      "Type": "/DataType/StdCppImplDataType/Duc/RequestBase"
    },
    {
      "Name": "aimsEcus",
      "Type": "/DataType/StdCppImplDataType/Duc/AimsEcuList"
    },
    {
      "Name": "retryTimes",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "mode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fingerprint",
      "Type": "/DataType/StdCppImplDataType/Duc/ByteArray"
    }
  ],
  "IsPlane": "false"
}