{
  "ShortName": "/DataType/StdCppImplDataType/Duc/PackageInfo",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "downloadUrl",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "zipSize",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32",
      "IsOptional": "false"
    },
    {
      "Name": "unzipSize",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32",
      "IsOptional": "false"
    },
    {
      "Name": "isRollback",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean",
      "IsOptional": "false"
    },
    {
      "Name": "key",
      "Type": "/HuaweiMDC/StdCppDataType/String",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}