{
  "ShortName": "/DataType/StdCppImplDataType/Duc/FinishCampaignRequest",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "requestBase",
      "Type": "/DataType/StdCppImplDataType/Duc/RequestBase"
    },
    {
      "Name": "finishType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "IsOptional": "false"
    },
    {
      "Name": "aimsEcu",
      "Type": "/DataType/StdCppImplDataType/Duc/AimsEcuList"
    }
  ],
  "IsPlane": "false"
}