{
  "ShortName": "/DataType/StdCppImplDataType/Duc/GetItfVersionResponse",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "responseBase",
      "Type": "/DataType/StdCppImplDataType/Duc/ResponseBase"
    },
    {
      "Name": "domainId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "ItfVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}