{
  "ShortName": "/DataType/StdCppImplDataType/Duc/CheckDownloadConditionRequest",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "requestBase",
      "Type": "/DataType/StdCppImplDataType/Duc/RequestBase"
    },
    {
      "Name": "packageInfos",
      "Type": "/DataType/StdCppImplDataType/Duc/PackageInfoList"
    },
    {
      "Name": "jointPackageInfos",
      "Type": "/DataType/StdCppImplDataType/Duc/PackageInfoList",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}