{
  "ShortName": "/DataType/StdCppImplDataType/di/EcuInfo",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ecuIdentity",
      "Type": "/DataType/StdCppImplDataType/di/EcuIdentity"
    },
    {
      "Name": "partitionType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "selfActivation",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    }
  ],
  "IsPlane": "true"
}