{
  "ShortName": "/DataType/StdCppImplDataType/di/GetUpdateCheckProgressResponse",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "responseBase",
      "Type": "/DataType/StdCppImplDataType/di/ResponseBase"
    },
    {
      "Name": "state",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "ecuErrorInfos",
      "Type": "/DataType/StdCppImplDataType/di/EcuErrorInfoArr",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}