{
  "ShortName": "/DataType/StdCppImplDataType/Duc/GetUpdateProgressRequest",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "requestBase",
      "Type": "/DataType/StdCppImplDataType/Duc/RequestBase"
    },
    {
      "Name": "queryEcus",
      "Type": "/DataType/StdCppImplDataType/Duc/EcuIdentityList"
    },
    {
      "Name": "stage",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}