{
  "ShortName": "/DataType/StdCppImplDataType/Duc/EcuDownloadStatus",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ecuIdentity",
      "Type": "/DataType/StdCppImplDataType/Duc/EcuIdentity"
    },
    {
      "Name": "state",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "5"
    },
    {
      "Name": "downloadedBytes",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "totalBytes",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    }
  ],
  "IsPlane": "true"
}