{
  "ShortName": "/DataType/StdCppImplDataType/di/RequestBase",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "taskId",
      "Type": "/DataType/StdCppImplDataType/di/string",
      "IsOptional": "false"
    },
    {
      "Name": "timestamp",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}