{
  "ShortName": "/DataType/StdCppImplDataType/di/EcuInventory",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ecuIdentity",
      "Type": "/DataType/StdCppImplDataType/di/EcuIdentity"
    },
    {
      "Name": "ecuId",
      "Type": "/DataType/StdCppImplDataType/di/string",
      "IsOptional": "false"
    },
    {
      "Name": "supplierInfo",
      "Type": "/DataType/StdCppImplDataType/di/string",
      "IsOptional": "false"
    },
    {
      "Name": "hardwareSerialNo",
      "Type": "/DataType/StdCppImplDataType/di/string",
      "IsOptional": "false"
    },
    {
      "Name": "hardwareVersion",
      "Type": "/DataType/StdCppImplDataType/di/string",
      "IsOptional": "false"
    },
    {
      "Name": "softwareSerialNo",
      "Type": "/DataType/StdCppImplDataType/di/string",
      "IsOptional": "false"
    },
    {
      "Name": "softwareVersions",
      "Type": "/DataType/StdCppImplDataType/di/VersionArr",
      "IsOptional": "false"
    },
    {
      "Name": "activatePartition",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}