{
  "ShortName": "/DataType/StdCppImplDataType/Duc/SetUpdateModeRequest",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "requestBase",
      "Type": "/DataType/StdCppImplDataType/Duc/RequestBase"
    },
    {
      "Name": "action",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "installEcus",
      "Type": "/DataType/StdCppImplDataType/Duc/EcuIdentityList",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}