{
  "ShortName": "/DataType/StdCppImplDataType/Duc/Version",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "softwares",
      "Type": "/DataType/StdCppImplDataType/Duc/VersionItemList",
      "IsOptional": "false"
    },
    {
      "Name": "firmwares",
      "Type": "/DataType/StdCppImplDataType/Duc/VersionItemList",
      "IsOptional": "false"
    },
    {
      "Name": "databases",
      "Type": "/DataType/StdCppImplDataType/Duc/VersionItemList",
      "IsOptional": "false"
    },
    {
      "Name": "configs",
      "Type": "/DataType/StdCppImplDataType/Duc/VersionItemList",
      "IsOptional": "false"
    },
    {
      "Name": "apps",
      "Type": "/DataType/StdCppImplDataType/Duc/VersionItemList",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}