{
  "ShortName": "/DataType/StdCppImplDataType/di/GetInventoryResultResponse",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "responseBase",
      "Type": "/DataType/StdCppImplDataType/di/ResponseBase"
    },
    {
      "Name": "state",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "ecuInventories",
      "Type": "/DataType/StdCppImplDataType/di/EcuInventoryArr",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}