{
  "ShortName": "/DataType/StdCppImplDataType/Duc/UploadLogRequest",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "requestBase",
      "Type": "/DataType/StdCppImplDataType/Duc/RequestBase"
    },
    {
      "Name": "uploadUrl",
      "Type": "/HuaweiMDC/StdCppDataType/String",
      "IsOptional": "false"
    },
    {
      "Name": "logType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "false"
}