{
  "ShortName": "/DataType/StdCppImplDataType/Duc/AimsEcu",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ecuInfo",
      "Type": "/DataType/StdCppImplDataType/Duc/EcuInfo"
    },
    {
      "Name": "softVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "calibrateVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}