{
  "ShortName": "/DataType/StdCppImplDataType/Duc/EcuInventory",
  "Namespace": "::symbol_0",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ecuIdentity",
      "Type": "/DataType/StdCppImplDataType/Duc/EcuIdentity"
    },
    {
      "Name": "ecuId",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "supplierInfo",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "hardwareSerialNo",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "hardwareVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "softwareSerialNo",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "softwareVersions",
      "Type": "/DataType/StdCppImplDataType/Duc/VersionList"
    },
    {
      "Name": "existImage",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "activatePartition",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "false"
}