{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/UpgradeDevObj",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "deviceName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "deviceStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "upgradeList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/UpdateInfoList"
    }
  ],
  "IsPlane": "false"
}