{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/LicmServiceInterface/LicmServiceInterface/GetProductLicenseStatusOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "GetLicStateType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/LicmMsgDataType/DataTypes/GetLicStateType"
    },
    {
      "Name": "GetStateResultType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/LicmMsgDataType/DataTypes/GetStateResultType"
    }
  ],
  "IsPlane": "true"
}