{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/Compensation",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "sourceID",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "targetID",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "sourceChannelMask",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "targetChannelMask",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "sourceSignalStartByte",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "targetSignalStartByte",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sourceLengthBit",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "targetLengthBit",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sourceByteOrder",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "targetByteOrder",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "compensationType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "offset",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "factor",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "mappingEnumTable",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/MappingEnumList"
    }
  ],
  "IsPlane": "false"
}