{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/ProbOdoInfo",
  "Namespace": "::mdc::probdistances",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "odoKappa",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "odoDrivenDistance",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "odoX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "odoYawAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "odoTimeStamp",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "odoY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "reserveMsg1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reserveMsg2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}