{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/MsgDataType/SomeipMsgDataType/Raw100DataImu",
  "Namespace": "::sensor::ins100::imu",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "imuGyroX",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "imuGyroY",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "imuGyroZ",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "imuAccX",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "imuAccY",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "imuAccZ",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "imuStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "7"
    },
    {
      "Name": "imuTemp",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "imuTimesynSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "7"
    },
    {
      "Name": "imuTimestamp",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "imuCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "2"
    },
    {
      "Name": "imuDataCrc32",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}