{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ChassisReportHeader",
  "Namespace": "::ara::chassis",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ChassisReportTime"
    },
    {
      "Name": "frame_id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}