{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp5",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "esp5LhfPulseCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "esp5LhfPulseCounterFailSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "esp5LhrPulseCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "esp5LhrPulseCounterFailSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "esp5RhfPulseCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "esp5RhfPulseCounterFailSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "esp5RhrPulseCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "esp5RhrPulseCounterFailSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}