{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/RadarMsgDataType/RadarState",
  "Namespace": "::ara::radar",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "sensorId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "nvmReadStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "nvmWriteStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "persistentError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "temporaryError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "interferenceError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "temperatureError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "voltageError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "maxDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "sortIndex",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "radarPower",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ctrlRelay",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "outputType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sendQuality",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sendExtinfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "motionRxState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rcsThreshold",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "blockError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "broadcastError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "electricAxisError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "configError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "calibrationError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "connectorDirection",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "can0WorkMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "can1WorkMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dualCanMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "timmingMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "powerMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "performanceMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "radarPosition",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hwError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "modulationStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "failureFlag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sleepSig",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "objAziAngleCalib",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}