{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/FrameSyncConfigParam",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "syncLength",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "syncData",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/Uint8List"
    }
  ],
  "IsPlane": "false"
}