{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/StatusInfo",
  "Namespace": "::ara::actcompensation",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "doorStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/DoorStatus"
    },
    {
      "Name": "epbLockStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "absStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "tcsStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "vdcStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "standStill",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "epsFunctionStyle",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "sasCalibration",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "steerMode",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "steerWarnLamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "keyStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "systemReadyStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    }
  ],
  "IsPlane": "true"
}