{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Eps2",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "epsAssistPraSwitchToLka",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epsHandsOffDetSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epsHandsOffDetStVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epsLkaCtrlAbortFeedback",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epsLkaCtrlDlvdValue",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "epsLkaCtrlDlvdValueVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epsLkaCtrlSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epsPasAbortFeedback",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epsPasEpasFailed",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epsPasReqFeedback",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}