{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/IfcMsgDataType/Version",
  "Namespace": "::ara::ifc",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "major",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "minor",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "patch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}