{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/WheelSpeed",
  "Namespace": "::mdc::ssm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "wheelDirection",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "wheelCount",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "wheelCountValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean",
      "Padding": "3"
    },
    {
      "Name": "wheelSpeedMps",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "wheelSpeedMpsValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}