{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/AutonomyMode",
  "Namespace": "::mdc::ssm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "autonomyLevel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "gearAutonomous",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "speedAutonomous",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "steeringAutonomous",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    }
  ],
  "IsPlane": "true"
}