{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssPasMsgDataType/ParkSlots",
  "Namespace": "::mdc::pasparkslots",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "slotId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "searchingStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "position",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "backgroundObjType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "length",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "parkSlotStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "depth",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "vehicleX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vehicleY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vehicleAlpha",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "objectList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssPasMsgDataType/ObstaclesInfoVec"
    },
    {
      "Name": "timeStamp",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "slotType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "obj1Angle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "obj2Angle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "reserveMsg1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reserveMsg2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "false"
}