{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/BrakeInfo",
  "Namespace": "::ara::chassis9000",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "brakePedal",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "brakePedalSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Uint8WithValid"
    },
    {
      "Name": "driverOverride",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Uint8WithValid"
    },
    {
      "Name": "mastCylinderPressure",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "mastCylinderPosition",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeTorque",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeForce",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeTorqueMax",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "driverDesiredTorque",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeTotalTqReq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "elecBrkTqReq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "hydrauBrkTqReq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeOverHeatStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aebAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aebActv",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "prefillAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "prefillActv",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brkCtrlAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brkCtrlActv",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espAbortFb",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "velocity",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "wheelSpeedFl",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/WheelSpeed"
    },
    {
      "Name": "wheelSpeedFr",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/WheelSpeed"
    },
    {
      "Name": "wheelSpeedRl",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/WheelSpeed"
    },
    {
      "Name": "wheelSpeedRr",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/WheelSpeed"
    },
    {
      "Name": "frontWhlIncTarTq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "frontWhlDecTarTq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "rearWhlIncTarTq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "rearWhlDecTarTq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "standstill",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Uint8WithValid",
      "Padding": "2"
    },
    {
      "Name": "roadFriction",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeTemperature",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "slope",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeStatusMaster",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brakeStatusSlave",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "commandFault",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbFaultStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbLockStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbButtonStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbOverride",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbClampForce",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "faultCode",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "autoHoldActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebdActive",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "ebdStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "absActive",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "absStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "escActive",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "escStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tcsActive",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "tcsStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "arpActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "arpFctAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "arpFailrSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dbfActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hdcActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hhcActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebaActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebaAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebaActvRank",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "awbAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "awbActv",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espABrkDegStWarning",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espABrkDegSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espPriBrStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbWorkMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brakeActualPedal",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeCmd",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeWorkMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}