{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcu300FConfigTranServiceInterface/DevmMcu300FConfigTranServiceInterface/GetConfigModeOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ConfigModeType",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/ConfigModeType"
    },
    {
      "Name": "ResultCode",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/ResultCode"
    }
  ],
  "IsPlane": "true"
}