{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UartFwdMsgDataType/UartBusDataType",
  "Namespace": "::ara::intfuartfwd",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UartFwdMsgDataType/Header"
    },
    {
      "Name": "data",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UartFwdMsgDataType/Uint8Vector"
    }
  ],
  "IsPlane": "false"
}