{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/Bcs8A",
  "Namespace": "::ara::actgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "bcsAbAactive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsAbAavailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsAbpActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsAbpAvailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsAebActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsAebAvailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsAwbActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsAwbAvailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsBrakeOverHeat",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsCddActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsCddAvailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsCddFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsMasterCylinderPr",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "bcsMasterCylinderPrOffset",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "bcsMasterCylinderPrOffsetVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsMasterCylinderPrVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsNoBrakeForce",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsQdcacc",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsVehicleStandStillSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}