{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeName",
  "Namespace": "::ara::tsync",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "DP_PRIMARY",
      "Value": "0"
    },
    {
      "Label": "SD_PRIMARY",
      "Value": "1"
    },
    {
      "Label": "MCU_PRIMARY",
      "Value": "2"
    },
    {
      "Label": "DP_SECONDARY",
      "Value": "3"
    },
    {
      "Label": "SD_SECONDARY",
      "Value": "4"
    },
    {
      "Label": "MCU_SECONDARY",
      "Value": "5"
    }
  ]
}