{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/NMmApaAvm",
  "Namespace": "::ara::chassischeryjx65sub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "nmapaAlActiveLoadMaster",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "nmapaControllerSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "nmapaCurrentFailSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "nmapaNcNetworkCommand",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "nmapaSyncBits",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}