{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/CameraInternalDataMethodServiceInterface/CameraInternalDataMethodServiceInterface/GetCameraInternalDataOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "CameraInternalData",
      "Type": "/HuaweiMDC/PlatformServiceInterface/CameraInternalDataMethodMsgDataType/CameraInternalData"
    }
  ],
  "IsPlane": "false"
}