{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/TimeStamp",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "year",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "month",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "day",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hour",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "minutes",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "seconds",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "mseconds",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "true"
}