{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/SonarInfoDataType",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "sonarInfoList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/SonarVec"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/Header"
    },
    {
      "Name": "msgRollingCounterFront",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "msgRollingCounterRear",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "false"
}