{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwEms2",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ems2BrakePedalStsForTcu",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ems2BrakePedalStsValidDataForTcu",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ems2EngineStsForDct",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}