{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/IfcMsgDataType/LineInfo",
  "Namespace": "::ara::ifc",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "lineId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "dy",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "curvChange",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "colorClass",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "curv",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "lineWidth",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "measureType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "typeConf",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "existProb",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "dxStart",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "dxEnd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "headingAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "reserved1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reserved2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}