{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/MasterData",
  "Namespace": "::ara::tsync",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "masterDataClk",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/TimeStampForSlaveTsync"
    },
    {
      "Name": "masterGnssClk",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/TimeStampForSlaveTsync"
    },
    {
      "Name": "pDelay",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/TimeStampForSlaveTsync"
    }
  ],
  "IsPlane": "true"
}