{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/RadarTrackMsgDataType/RadarTrack",
  "Namespace": "::ara::rtrack",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "idState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "lifetime",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vx",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vy",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "ax",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "ay",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "rcs",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "snr",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "xRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "yRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "zRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vxRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vyRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "axRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "ayRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "orientation",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "orientRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "yawRate",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "heading",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "length",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "width",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "height",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "fusionSig",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fusionCamID",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "yawRateRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "lengthRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "widthRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "heightRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "xQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "yQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "zQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vxQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vyQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "axQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "ayQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "orientationQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "yawRateQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "lengthQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "widthQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "heightQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "underpassProbability",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "overpassProbability",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "existProbability",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "movProperty",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "trackState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "trackType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "referencePoint",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "motionDirection",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    }
  ],
  "IsPlane": "true"
}