{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/CanBusConfigParamElem",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "channelId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "baudRate",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "prescale",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "initCycleSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rxIdList",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/RxIdList"
    },
    {
      "Name": "txIdList",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/TxIdList"
    },
    {
      "Name": "usrReserved",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/Uint8List"
    }
  ],
  "IsPlane": "false"
}