{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/EchoDistanceInfo",
  "Namespace": "::mdc::detectdistances",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "leftEcho",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/EchoInfo"
    },
    {
      "Name": "midEcho",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/EchoInfo"
    },
    {
      "Name": "rightEcho",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/EchoInfo"
    }
  ],
  "IsPlane": "true"
}