{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VoSerializerMsgDefinitions/DataTypes/ResetResult",
  "Namespace": "::mdc::vo",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "VO_SER_RUNNING",
      "Value": "0"
    },
    {
      "Label": "VO_SER_ABNORMAL",
      "Value": "1"
    },
    {
      "Label": "VO_SER_OFFLINE",
      "Value": "2"
    }
  ]
}