{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/McuCanNetWorkServiceInterface/McuCanNetWorkServiceInterface/GetWorkModeOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "UInt32",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "UInt8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}