{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/MntAgentMsgDataTypes/DelayDataType/DelayEventDataType",
  "Namespace": "::mdc::mnt",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "action",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "quantity",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    },
    {
      "Name": "module",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "target",
      "Type": "/HuaweiMDC/PlatformServiceInterface/MntAgentMsgDataTypes/DelayDataType/StringVector"
    }
  ],
  "IsPlane": "false"
}