{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/AdapteConditionServiceInterface/AdapterConditionInterface/ConditionOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "uint16_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint16_t"
    },
    {
      "Name": "uint8_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}