{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/TimeSource",
  "Namespace": "::ara::tsync",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "USE_GNSS_TIME",
      "Value": "0"
    },
    {
      "Label": "USE_LOCAL_TIME",
      "Value": "1"
    },
    {
      "Label": "USE_GPTP_TIME",
      "Value": "2"
    }
  ]
}