{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/NmMsgDataTypes/DataTypes/RemoteSleepIndicationData",
  "Namespace": "::ara::nm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "networkHandle",
      "Type": "/HuaweiMDC/PlatformServiceInterface/NmMsgDataTypes/DataTypes/NetworkHandleDecl"
    },
    {
      "Name": "indication",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}