{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Dms1",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "dmsDrvrDetSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dmsInterestsRegion",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dmsL3DriverDistractionSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "dmsL3DriverFatigueSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "dmsSysErrSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}