{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/AreaDistance",
  "Namespace": "::mdc::areadistances",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "areaDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "reserveMsg1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reserveMsg2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}