{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp7",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "esp7AbpActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp7AbpAvailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp7AeBdecActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp7AeBdecAvailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp7EscApaLcAvailability",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp7EspApaLcFailureSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp7EspApaLcStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp7LhrWheelDriveDirection",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp7LhrWheelSpeedRaw",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "esp7LhrWheelSpeedRawValidData",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp7RhrWheelDriveDirection",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "esp7RhrWheelSpeedRaw",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "esp7RhrWheelSpeedRawValidData",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}