{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwDcm1I",
  "Namespace": "::ara::chassisgaca13ican",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "fldcmFlWinSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fldcmMirrorFoldUnfoldSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fldcmMirrorFoldUnfoldSwitchSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fldcmRlWinSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frdcmFrWinSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frdcmMirrorFoldUnfoldSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frdcmRrWinSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}