{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActGacParking100SubDataType/ActGacParking100Msg",
  "Namespace": "::ara::actgacparking100",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/ActCommonHeader"
    },
    {
      "Name": "avpLearningPathNum1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathLearnRate1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathType1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningLotType1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathSt1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath1Src",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathDst1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathNum2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathLearnRate2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathType2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningLotType2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathSt2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathNum3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathLearnRate3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathType3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningLotType3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathSt3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath3Src",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathDst3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathNum4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathLearnRate4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathType4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningLotType4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathSt4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath4Src",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathDst4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaIconTwinkle",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaParkSlotChoiceL2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaParkSlotChoiceR2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath3MatGpsSucces",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath4MatGpsSucces",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpResRouteLeg",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathNum5",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathLearnRate5",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathType5",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningLotType5",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathSt5",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath5Src",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathDst5",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathNum6",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathLearnRate6",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathType6",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningLotType6",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathSt6",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath6Src",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathDst6",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaParkSlotChoiceL3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaParkSlotChoiceR3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath5MatGpsSucces",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath6MatGpsSucces",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpUseActDis",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathNum7",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathLearnRate7",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathType7",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningLotType7",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathSt7",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath7Src",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathDst7",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathNum8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathLearnRate8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathType8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningLotType8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathSt8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath8Src",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathDst8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaParkSlotChoiceL4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaParkSlotChoiceR4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath7MatGpsSucces",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath8MatGpsSucces",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpProcRat",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathType9",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningLotType9",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathSt9",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath9Src",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathDst9",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathNum10",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathLearnRate10",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathType10",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningLotType10",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathSt10",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath10Src",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathDst10",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath9MatGpsSucces",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath10MatGpsSucces",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpLearningProcessInfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpLearningFailedInfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaAvpFreeparkingUsability",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathUniqueId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reserved2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reserved3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath2Src",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathDst2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath1MatGpsSucces",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPath2MatGpsSucces",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLrngDst",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpLearningPathNum9",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpPathLearnRate9",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasWarnTone",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved5",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaApaActFuncInd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaApaAuthst",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaRpaShortPresSuppSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaPasCommandDoorsUnlock",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaRpaReady",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaIgOffReqEnable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaRearMirrorFoldReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaRearMirrorUnFoldReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapapGearReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapapGearReqEnable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsAcuDisplayReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaSlotSelectFebk",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpCtrlSigSrc",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaAvpParkSlotInfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved6",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHavpUseTolTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved7",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaSwitchStShow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "avpHvacCtrlReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaIhuVoiceReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaHavpSwitchStShow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaPavpSwitchStShow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSystemType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasButtonPress",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSideZoneStatusF",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSideZoneStatusR",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasRrMidDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasRlMidDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasRrDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasRlDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasRslSideDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasRsrSideDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasFrDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasFlDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasFrMidDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasFlMidDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasFsrSideDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasFslSideDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsSystemSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsVrSwitchFailSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsFrontCameraFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsLeftCameraFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsRightCameraFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsRearCameraFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsSystemType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsCalibrateSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaVideoSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsAcuApkDisplayReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsSingleViewInd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsModEnalbe",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcs3dEnalbe",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsOperationSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsPasButtonPress",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsMmiapaConfirmButton",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pcsMmiapaFuncSelect",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaBcmLowBeamReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaBcmParkLampReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaPasCommandDoorsLock",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaWindowCloseReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaHighBeamLampReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaHornReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaWiperReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaWaterSprayReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaAvasReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaVoiceReminderSwitchSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaRaFuncSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaParkSlotChoiceL1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaParkSlotChoiceR1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}