{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/TyreStatus",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "tyrePressureValue",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "tyrePressureLeakageStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/BodyReportUint8WithValid"
    },
    {
      "Name": "tyrePressureTirePStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/BodyReportUint8WithValid"
    }
  ],
  "IsPlane": "true"
}