{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/RadarMrrEpsElkSubDataType/RadarMrrEpsElkMsg",
  "Namespace": "::ara::radarmrrepselk",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/RadarMrrEpsElkSubDataType/RadarMrrHeader"
    },
    {
      "Name": "motorTorqueUpperLimit",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "motorTorqueLowerLimit",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "adasAngleReqSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adasAngleReq",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "elkOtFaultStatusFla",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "elkStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "elkTakeOverReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved1",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "reserved2",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "false"
}