{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/CommonStatus",
  "Namespace": "::ara::body9000",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "hornStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "mileage",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vin",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/VinData"
    },
    {
      "Name": "interiorTemperature",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/BodyReportFloat32WithValid"
    },
    {
      "Name": "outsideTemperature",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/BodyReportFloat32WithValid"
    },
    {
      "Name": "keyStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "batterySocStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "powerSocStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dcdcState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "gapStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rearViewMirrorStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rainLightSensorStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "powerMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "engineRun",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "chargingStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}