{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/ChassisReport9000Msg",
  "Namespace": "::ara::chassis9000",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "autoMode",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/AutonomyMode"
    },
    {
      "Name": "velocity",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "steerAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "frontWheelAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "actualGear",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/Gear"
    },
    {
      "Name": "master",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/ActuatorStatus"
    },
    {
      "Name": "slave",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/ActuatorStatus"
    },
    {
      "Name": "steer",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/SteerInfo"
    },
    {
      "Name": "brake",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/BrakeInfo"
    },
    {
      "Name": "vcu",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/ThrottleInfo"
    },
    {
      "Name": "gear",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/GearInfo"
    },
    {
      "Name": "egoMotion",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/VehicleMotion"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Chassis9000MsgDataType/ChassisReportHeader"
    }
  ],
  "IsPlane": "false"
}