{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DataType/CapData",
  "Namespace": "::ara::dcap",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "objectId",
      "Type": "/HuaweiMDC/StdCppDataType/String",
      "IsOptional": "false"
    },
    {
      "Name": "timeStamp",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t",
      "IsOptional": "false"
    },
    {
      "Name": "sequenceId",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t",
      "IsOptional": "false"
    },
    {
      "Name": "payloadSize",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t",
      "IsOptional": "false"
    },
    {
      "Name": "payload",
      "Type": "/HuaweiMDC/StdCppDataType/String",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}