{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/InsSensorInfoMsgDataType/SensorInfo",
  "Namespace": "::mdc::sensorinfo",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/GnssInfoDataType/Header"
    },
    {
      "Name": "length",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "data",
      "Type": "/HuaweiMDC/ApplicationDataType/Uint8Vector"
    }
  ],
  "IsPlane": "false"
}