{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/SensorInfo",
  "Namespace": "::ara::actcompensation",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "insideTemperature",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Float32WithValid"
    },
    {
      "Name": "outsideTemperature",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Float32WithValid"
    },
    {
      "Name": "relativeHumidity",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint16WithValid"
    },
    {
      "Name": "rainLightSensor",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    },
    {
      "Name": "rainfall",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Uint8WithValid"
    }
  ],
  "IsPlane": "true"
}