{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/InsStatusInfoMsgDataType/InsStatusInfo",
  "Namespace": "::mdc::ins",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/GnssInfoDataType/Header"
    },
    {
      "Name": "posInitStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "velInitStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "headingInitStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "attitudeInitStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "insInitStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "whlspdfusionStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "faultStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reversed1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reversed2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reversed3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reversed4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "false"
}