{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/EpsNm",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "epsNmDataField1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "epsNmDataField2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "epsNmWakeupOrigin",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epsNodeAddress",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epsSubNetWakeRq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}