{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/NrmcMsgDataTypes/DomainConfigObj",
  "Namespace": "::mdc::nrm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "domainType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "vlanIntfs",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/StringList"
    }
  ],
  "IsPlane": "false"
}