{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TimeDelayDataType/CamDelayData",
  "Namespace": "::ara::camera",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "frameId",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "ispCostTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "ispRecvTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "intfCostTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "intfRecvTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "cmSendTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "false"
}