{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/CanTpMsgDataType/CanTpHeader",
  "Namespace": "::ara::cantp",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/CanTpMsgDataType/CanTpTime"
    },
    {
      "Name": "frame_id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}