{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmSamServiceInterface/DevmSamServiceInterface/GetSensorInfoOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "DeviceInfo",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/DeviceInfo"
    },
    {
      "Name": "Int32",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    }
  ],
  "IsPlane": "false"
}