{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/BodyReportMsg",
  "Namespace": "::ara::body",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "lightSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/LightSwitch"
    },
    {
      "Name": "modeSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/ModeSwitch"
    },
    {
      "Name": "mirrorSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/MirrorSwitch"
    },
    {
      "Name": "wiperFrontSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/Wiper"
    },
    {
      "Name": "wiperRearSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/Wiper"
    },
    {
      "Name": "wiperFrontStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/Wiper"
    },
    {
      "Name": "wiperRearStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/Wiper"
    },
    {
      "Name": "padSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/PadSwitch"
    },
    {
      "Name": "lightStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/LightStatus"
    },
    {
      "Name": "doorStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/DoorStatus"
    },
    {
      "Name": "doorSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/DoorSwitch"
    },
    {
      "Name": "windowStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/WindowStatus"
    },
    {
      "Name": "tyreFlStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/TyreStatus"
    },
    {
      "Name": "tyreFrStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/TyreStatus"
    },
    {
      "Name": "tyreRlStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/TyreStatus"
    },
    {
      "Name": "tyreRrStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/TyreStatus"
    },
    {
      "Name": "safetyStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/SafetyStatus"
    },
    {
      "Name": "commonStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/CommonStatus"
    },
    {
      "Name": "pepsSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/PepsSwitch"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/BodyReportHeader"
    }
  ],
  "IsPlane": "false"
}