{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/MsgDataType/CanMsgDataType/Element",
  "Namespace": "::mdc::mdccan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "timeStamp",
      "Type": "/HuaweiMDC/MdcPlatformServices/MsgDataType/CanComMsgType/Systemtime"
    },
    {
      "Name": "canId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "validLen",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "data",
      "Type": "/HuaweiMDC/MdcPlatformServices/MsgDataType/CanMsgDataType/CanData"
    }
  ],
  "IsPlane": "false"
}