{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/IfcMsgDataType/IfcArray",
  "Namespace": "::ara::ifc",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/IfcMsgDataType/Header"
    },
    {
      "Name": "version",
      "Type": "/HuaweiMDC/PlatformServiceInterface/IfcMsgDataType/Version"
    },
    {
      "Name": "vdCipvId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcwValidFlag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcwValidFlagId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "isDrivingOnHighWayVideo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "roadCurvatureFar",
      "Type": "/HuaweiMDC/StdCppDataType/Int16"
    },
    {
      "Name": "curveDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "rampDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "tunnelDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "tollStationDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "roadCurvature",
      "Type": "/HuaweiMDC/StdCppDataType/Int16"
    },
    {
      "Name": "speedLimitDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "isDrivingOnRightLane",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bridgeDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "isEnterTunnelInfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "isDrivingOnHighWayMap",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "isCameraErrorType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "isFormOfWay",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "starRampDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "isMapDataValid",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "stopRampDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "navSpdLimUnit",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "objCount",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "objESSActvFlg",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "failsafeInhibitAcc",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "state",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lckStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "handsoffDetected",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dtcStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "handsoffWarning",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "speedLimit",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "objHdrTimeStamp",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "autosarTimeStampHigh",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "autosarTimeStampLow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "essFuncSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vruFlag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "turnAssistFlag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vruTurnFlag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "c2cflag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "mcpId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "cipvId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "turnAssitId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "mcpTrunId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vibrationWarning",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "angleCmdReqValue",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "angleCmdReqProtnValue",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "funcAngleCmdReqFlag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "torqFactReq",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "synchronizationState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "ldwSwitchStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lkaSwitchStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lckSwitchStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "elkSwitchStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aesSwitchStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ldwSensitivity",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hutAvailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "essPedResp",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "essVehResp",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lssWarnFormStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lssStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "intelligentEvaResp",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aesStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "essStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aesErrStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "essErrStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "handsOffWarn",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "calibrationStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "cameraBlockageStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ldwWarn",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lssIntervention",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lssFuncStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "elkMainState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "laneAvailability",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tjaFollowStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lssErrStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aesIntervention",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "essIntervention",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "elkActStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "intelligentEvaActSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lckStatusIndicator",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tsrSwitchStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tsrSpeedLimitUnit",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tsrSpeedLimit",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tsrSpeedLimitCfdc",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tsrStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tsrSpeedLimitStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tsrConfidience",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tsrTrafficSign",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "tsrSpeedLimitWarn",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tsrWarnStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tsrSensitivity",
      "Type": "/HuaweiMDC/StdCppDataType/Int8"
    },
    {
      "Name": "hmaStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hmaHibeamReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "cameraStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "trafficStyle",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "roadIllumDetd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ambLight",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "abaLevel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "abaReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebaTgtDecelReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aebVehHldReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aebTgtDecelReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aebTgtDecelReqValue",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "awbReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "awbLevel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "abpReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brkReqFunc",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "objSty",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pedSwitchStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vehSwitchStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcwSensitive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "jaSwitchStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vehTrig",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pedTrig",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vehFctStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pedFctStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcwWarn",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "jaFuncStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "jaWarn",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "jaBrkTrig",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "freshnessValue",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "macCheck",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "reserved1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reserved2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "spotInfoList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/IfcMsgDataType/SpotInfoVec"
    },
    {
      "Name": "lineInfoList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/IfcMsgDataType/LineInfoVec"
    }
  ],
  "IsPlane": "false"
}