{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/ConfigServerMsgDataType/ImplementationDataTypes/ServerNotifyData",
  "Namespace": "::mdc::config::server",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "notifyType",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "clientName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "extraData",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}