{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/RmCenterServiceInterface/RmCenterServiceInterface/GetMemLoadRateOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "UInt32",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "Int8",
      "Type": "/HuaweiMDC/StdCppDataType/Int8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}