{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/ChassisGacA13AcanStatusMsg",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "epsNm",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/EpsNm"
    },
    {
      "Name": "eps2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Eps2"
    },
    {
      "Name": "bcs10A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Bcs10A"
    },
    {
      "Name": "gwAcu1aA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwAcu1aA"
    },
    {
      "Name": "gwAcu37bA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwAcu37bA"
    },
    {
      "Name": "gwAcu10A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwAcu10A"
    },
    {
      "Name": "vcu2A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Vcu2A"
    },
    {
      "Name": "gwSrs2A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwSrs2A"
    },
    {
      "Name": "bcsNm",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/BcsNm"
    },
    {
      "Name": "gwBcmRls1bA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwBcmRls1bA"
    },
    {
      "Name": "vcu21A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Vcu21A"
    },
    {
      "Name": "gwTel3eA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwTel3eA"
    },
    {
      "Name": "vcu13A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Vcu13A"
    },
    {
      "Name": "gwmNmAcan",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwmNmAcan"
    },
    {
      "Name": "bcs7A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Bcs7A"
    },
    {
      "Name": "gwHod1A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwHod1A"
    },
    {
      "Name": "gwAcu2A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwAcu2A"
    },
    {
      "Name": "ebb2A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Ebb2A"
    },
    {
      "Name": "gwBcm2A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwBcm2A"
    },
    {
      "Name": "gwBcm1A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwBcm1A"
    },
    {
      "Name": "gwAcu3aA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwAcu3aA"
    },
    {
      "Name": "gwAcu35bA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwAcu35bA"
    },
    {
      "Name": "tel2A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Tel2A"
    },
    {
      "Name": "tel1A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Tel1A"
    },
    {
      "Name": "dmsNm",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/DmsNm"
    },
    {
      "Name": "bcs9A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Bcs9A"
    },
    {
      "Name": "funcDiagRx",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/FuncDiagRx"
    },
    {
      "Name": "gwSrs1A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwSrs1A"
    },
    {
      "Name": "vcu9A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Vcu9A"
    },
    {
      "Name": "gwAcu10aA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwAcu10aA"
    },
    {
      "Name": "gwAcu2aA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwAcu2aA"
    },
    {
      "Name": "bcsEpb2A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/BcsEpb2A"
    },
    {
      "Name": "dms1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Dms1"
    },
    {
      "Name": "gwTel10bA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwTel10bA"
    },
    {
      "Name": "bcs5A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Bcs5A"
    },
    {
      "Name": "gwIcm1A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwIcm1A"
    },
    {
      "Name": "ifcNm",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/IfcNm"
    },
    {
      "Name": "vcu14A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Vcu14A"
    },
    {
      "Name": "bcs11A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Bcs11A"
    },
    {
      "Name": "eps1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Eps1"
    },
    {
      "Name": "ebbNm",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/EbbNm"
    },
    {
      "Name": "vcuNmAcan",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/VcuNmAcan"
    },
    {
      "Name": "adasPhysDiagRx",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/AdasPhysDiagRx"
    },
    {
      "Name": "telNmAcan",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/TelNmAcan"
    },
    {
      "Name": "bcs6A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Bcs6A"
    },
    {
      "Name": "bcsEpb1A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/BcsEpb1A"
    },
    {
      "Name": "gwTel11bA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwTel11bA"
    },
    {
      "Name": "gwIcmHvacA",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwIcmHvacA"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/ActCommonHeader"
    },
    {
      "Name": "tel19A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Tel19A"
    },
    {
      "Name": "gw3A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Gw3A"
    },
    {
      "Name": "dms2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Dms2"
    }
  ],
  "IsPlane": "false"
}