{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmSamServiceInterface/DevmSamServiceInterface/ImportDataDefineOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "UpdateInfo",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/UpdateInfo"
    },
    {
      "Name": "UpgradeInfo",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/UpgradeInfo"
    },
    {
      "Name": "UpdateInfoList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/UpdateInfoList"
    },
    {
      "Name": "UpgradeDevObj",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/UpgradeDevObj"
    },
    {
      "Name": "UpgradeDevList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/UpgradeDevList"
    },
    {
      "Name": "ConfItem",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/ConfItem"
    },
    {
      "Name": "Items",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/Items"
    },
    {
      "Name": "Uint8List",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/Uint8List"
    }
  ],
  "IsPlane": "false"
}