{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/SlaveData",
  "Namespace": "::ara::tsync",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "slaveRecvDataClk",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/TimeStampForSlaveTsync"
    },
    {
      "Name": "slaveRecvGnssClk",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/TimeStampForSlaveTsync"
    },
    {
      "Name": "slaveSendDataClk",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/TimeStampForSlaveTsync"
    },
    {
      "Name": "slaveSendGnssClk",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/TimeStampForSlaveTsync"
    },
    {
      "Name": "slaveDataDelta",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/TimeDelta"
    },
    {
      "Name": "slaveGnssDelta",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMcuDataTypes/DataTypes/TimeDelta"
    }
  ],
  "IsPlane": "true"
}