{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/OffsetInfo",
  "Namespace": "::ara::actgac",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "axOffset",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "ayOffset",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "azOffset",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "yawRateOffset",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "pitchRateOffset",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "rollRateOffset",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}