{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/AdapterDidServiceInterface/AdapterDataIdentifierInterface/AdapterReadOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "uint16_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint16_t"
    },
    {
      "Name": "uint8_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "uint32_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    },
    {
      "Name": "uint8Array",
      "Type": "/HuaweiMDC/AdapterDataType/uint8Array"
    }
  ],
  "IsPlane": "false"
}