{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/LicmServiceInterface/LicmServiceInterface/UpdateLicenseOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "Int32",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "GetStateResultType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/LicmMsgDataType/DataTypes/GetStateResultType",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}