{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp4",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "esp4AbAactive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp4AbAavailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp4AwBactive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp4AwBavailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp4CddActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp4CddAvailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp4DcFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp4EcdTempOff",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp4LhrWheelSpeedRpm",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "esp4RhrWheelSpeedRpm",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "esp4VehicleStandstill",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp4VlcActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp4VlcAvailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "esp4VlcInternalTargetAcceleration",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}