{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlServiceInterface/DevmMcuCtrlSomeipServiceInterface/GetSysPowerOffInfoOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "UtcDateTime",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlMsgDataTypes/DataTypes/UtcDateTime"
    },
    {
      "Name": "UInt8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "UInt8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}