{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlMsgDataTypes/DataTypes/UtcDateTime",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "year",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "month",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "day",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hour",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "minute",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "second",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "msecond",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "true"
}