{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/UartMsgDataType/UartDataParam",
  "Namespace": "::mdc::mdcuart",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "timeStamp",
      "Type": "/HuaweiMDC/MdcPlatformServices/UartMsgDataType/Systemtime"
    },
    {
      "Name": "validLen",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "data",
      "Type": "/HuaweiMDC/MdcPlatformServices/UartMsgDataType/UartData"
    }
  ],
  "IsPlane": "false"
}