{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActGacParking20SubDataType/ActGacParking20Msg",
  "Namespace": "::ara::actgacparking20",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/ActCommonHeader"
    },
    {
      "Name": "ctrlEndOk",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ctrlPathId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ctrlOffTrack",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ctrlObsDetected",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "steerAngReq",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "stopDistReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "spdLimitReq",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "gearReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brkType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hpaArbState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaChallenge1Tel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaChallenge2Tel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaChallengeReceive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaLsmVehSecReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaLsmPrefill",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaLsmNudgeReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaDriverPresenceExternal",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaBcmTurnLampReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasApaButtonPress",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaSafeDrvrHandoverReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaLsmVehDirRq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaLsmComfBrakeReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasParkSideSel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasFrontObjExist",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasApaBrkFuncMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasApaBrkModeSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaTimeStampYear",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaTimeStampMonth",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaTimeStampDay",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaTimeStampHour",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaTimeStampMin",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaTimeStampSec",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaTimeStampMilliSec",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaDvrTriggerId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaDvrTrigger",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaVehTorqLimitEnable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "paaVehTorqLimit",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasApaModeInd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaPasRemoteParkingMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaPasRemoteParkingEnable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasApaPwrModeReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasVrSwitchFailSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasApaQuitInd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasApaRecInd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasApaDrvReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaRpaChallenge1Sbm",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fapaRpaChallenge2Sbm",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaVoiceReminder",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasBackParkDisplayReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved5",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}