{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/BrakeInfo",
  "Namespace": "::ara::chass::repbakup",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "brakePedal",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "brakePedalSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Uint8WithValid"
    },
    {
      "Name": "driverOverride",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Uint8WithValid"
    },
    {
      "Name": "mastCylinderPressure",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "mastCylinderPosition",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeTorque",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeForce",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeTorqueMax",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "driverDesiredTorque",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeTotalTqReq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "elecBrkTqReq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "hydrauBrkTqReq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeOverHeatStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aebAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aebActv",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "prefillAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "prefillActv",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brkCtrlAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brkCtrlActv",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espAbortFb",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "velocity",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "wheelSpeedFl",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/WheelSpeed"
    },
    {
      "Name": "wheelSpeedFr",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/WheelSpeed"
    },
    {
      "Name": "wheelSpeedRl",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/WheelSpeed"
    },
    {
      "Name": "wheelSpeedRr",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/WheelSpeed"
    },
    {
      "Name": "frontWhlIncTarTq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "frontWhlDecTarTq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "rearWhlIncTarTq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "rearWhlDecTarTq",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "standstill",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Uint8WithValid",
      "Padding": "2"
    },
    {
      "Name": "roadFriction",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeTemperature",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "slope",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid"
    },
    {
      "Name": "brakeStatusMaster",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brakeStatusSlave",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "commandFault",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbFaultStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbLockStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbButtonStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbOverride",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "epbClampForce",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "faultCode",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "autoHoldActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebdActive",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "ebdStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "absActive",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "absStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "escActive",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "escStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tcsActive",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "tcsStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "arpActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "arpFctAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "arpFailrSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dbfActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hdcActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hhcActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebaActvSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebaAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebaActvRank",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "awbAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "awbActv",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espABrkDegStWarning",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espABrkDegSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espPriBrStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "abaActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "abaAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "abpActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "abpAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aebBaActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "aebIbActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "btcActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "btcRaActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "cdpActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ctaBrkAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "drivingMod",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espFuncOffSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ptcActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ptcRaActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "msrActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "msrRaActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vdcActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espDstSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espHwpActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espHwpAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "driverOverrideAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "driverOverrideDomAv",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "espDiagActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brakeLightSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "reds",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/BrakeRedInfo"
    }
  ],
  "IsPlane": "true"
}