{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/LicmMsgDataType/DataTypes/LicSubInfoType",
  "Namespace": "::mdc::license",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "licType",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "validDate",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "upgradeDate",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}