{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/NrmcMsgDataTypes/PortConfigObj",
  "Namespace": "::mdc::nrm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "portName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "portScope",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "vlanIntfs",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/StringList"
    },
    {
      "Name": "portType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "false"
}