{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/LicmServiceInterface/LicmServiceInterface/GetAnnualFeeValidDateOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "GetStateResultType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/LicmMsgDataType/DataTypes/GetStateResultType"
    },
    {
      "Name": "String",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}