{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/RadarMsgDataType/TimeStampInfo",
  "Namespace": "::ara::radar",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "timeStampStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "6"
    },
    {
      "Name": "timeStamp",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "autoSarTimeStamp",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "reserved1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "reserved2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    }
  ],
  "IsPlane": "true"
}