{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/InsGsvMsgDataType/SatelliteInfo",
  "Namespace": "::mdc::gsv",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "gsvName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "prn",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "elevation",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "azimuth",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "snr",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "signalId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}