{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/PackageInfoType",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "headType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dataType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frameSyncConfig",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/FrameSyncConfigParam"
    },
    {
      "Name": "packageHeadIdConfig",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/HeadLengthConfigPara"
    },
    {
      "Name": "packageLengthConfig",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/DataLengthConfigPara"
    },
    {
      "Name": "packageChecksumConfig",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/PackageChecksumConfigPara"
    }
  ],
  "IsPlane": "false"
}