{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/PadSwitch",
  "Namespace": "::ara::body9000",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "up",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "down",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "left",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "right",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ok",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}