{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp1",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "esp1AbsActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1AbsFailSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1EbdFailSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1HdcCtrlSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1HdcFailSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "esp1PressureMasterCylinder",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "esp1PressureMasterCylinderValidData",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1SwitchOffCruiseControl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1TcsActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1TcsFailSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1VdcActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1VdcControlSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1VdcControlStsValidData",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1VdcFailSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp1VehicleSpeedVsoSig",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "esp1VehicleSpeedVsoSigValidData",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}