{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlServiceInterface/DevmMcuCtrlSomeipServiceInterface/GetMcuVersionOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "VersionResultType",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlMsgDataTypes/DataTypes/VersionResultType"
    },
    {
      "Name": "VersionResultType",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlMsgDataTypes/DataTypes/VersionResultType"
    },
    {
      "Name": "VersionResultType",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlMsgDataTypes/DataTypes/VersionResultType"
    },
    {
      "Name": "UInt8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}