{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/Yas1",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "yas1LateraAccaleleration",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "yas1LateralelerationSigValidData",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "yas1YawRate",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "yas1YawRateSigValidData",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}