{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/Float32WithValid",
  "Namespace": "::ara::actcompensation",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "value",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "confidence",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}