{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/ApaDataType",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "echo1Distance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "echo1Width",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "echo1Peak",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "echo2Distance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "echo2Width",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "echo2Peak",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "blind",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rollingCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "confidence",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/Header"
    },
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "false"
}