{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/TyreStatus",
  "Namespace": "::ara::body9000",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "tyrePressureValue",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "tyrePressureLeakageStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/BodyReportUint8WithValid"
    },
    {
      "Name": "tyrePressureTirePStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/BodyReportUint8WithValid"
    }
  ],
  "IsPlane": "true"
}