{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisReportMsgDataType/ChassisReportHeader",
  "Namespace": "::ara::chass::report",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisReportMsgDataType/ChassisReportTime"
    },
    {
      "Name": "frame_id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}