{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/PackageChecksumConfigPara",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "checksumSignalStartPosStartByte",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "checksumSignalLengthSize",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "checksumType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}