{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorStatus",
  "Namespace": "::ara::chassis",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "angleSteer",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "torqueSteer",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "emergencyAngleSteer",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "emergencyTorqueSteer",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "steerVibrate",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "accelerate",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "decelerate",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "emergencyDecelerate",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "drive",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "brake",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "vlc",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "emergencyStop",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "stop",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "park",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    },
    {
      "Name": "gear",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisMsgDataType/ActuatorWorkStatus"
    }
  ],
  "IsPlane": "true"
}