{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/BrakeInfo",
  "Namespace": "::ara::actgac",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "wheelSpeedFl",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/WheelSpeedInfo"
    },
    {
      "Name": "wheelSpeedFr",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/WheelSpeedInfo"
    },
    {
      "Name": "wheelSpeedRl",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/WheelSpeedInfo"
    },
    {
      "Name": "wheelSpeedRr",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/WheelSpeedInfo"
    },
    {
      "Name": "brakePedal",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    },
    {
      "Name": "velocity",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    },
    {
      "Name": "masterMotorSpeed",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Uint32WithValid"
    },
    {
      "Name": "slaveMotorSpeed",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Uint32WithValid"
    }
  ],
  "IsPlane": "true"
}