{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/UssInfoList",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "directDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "blind",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rollingCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "confidence",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "crossDistanceLeft",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "crossDistanceRight",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}