{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/EcuDataType",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "pasEcuInfoVerHard",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "pasEcuSInfoVerSoft",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "pasEcuInfoVerBoot",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "pasEcuInfoDateYear",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "pasEcuInfoDateMonth",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "pasEcuInfoDateDay",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "vinDataIdentifierHigh",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vinDataIdentifierMiddle",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "vinDataIdentifierLow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/Header"
    },
    {
      "Name": "pasEcuPartNrHigh",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasEcuPartNrLow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "pasEcuSupplierIdHigh",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "pasEcuSupplierIdLow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "pasEcuSerialNumber",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "pasEcuSoftwareFingerPrintId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "pasEcuVariantCode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "pasEcuInfoVerSoftSupplier",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "msgRollingCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "false"
}