{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/Bcs3A",
  "Namespace": "::ara::actgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "bcsApaGrarLvlReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsApaGrarLvlReqVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsApaTorqReqEv",
      "Type": "/HuaweiMDC/StdCppDataType/Int16"
    },
    {
      "Name": "bcsApaTorqReqSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsHbbIntervention",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "bcsTargetRecpTorqRqFa",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "bcsTargetRecpTorqRqFaSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}