{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/ProbEchoDistanceInfo",
  "Namespace": "::mdc::probdistances",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "leftEcho",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/ProbEchoInfo"
    },
    {
      "Name": "midEcho",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/ProbEchoInfo"
    },
    {
      "Name": "rightEcho",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/ProbEchoInfo"
    }
  ],
  "IsPlane": "true"
}