{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwIcm5",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "icm5AccKilometreMile",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "icm5DriverSeatBeltSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "icm5DriverSeatBeltSwitchQbit",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}