{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/FaultData",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "faultId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "faultObject",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "faultSate",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "faultType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "faultLevel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "faultSource",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "faultTime",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/TimeStamp"
    },
    {
      "Name": "faultDesc",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/BufArray64"
    }
  ],
  "IsPlane": "false"
}