{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Vcu9A",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "vcuBrkPedPst",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vcuBrkPedPstVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "vcuBrkVcuuPress",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "vcuBrkVcuuPressVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vcuCrntGearLvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vcuCrntGearLvlVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "vcuRecpTorqFa",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "vcuRecpTorqFavd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}