{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/IfcMsgDataType/SpotInfo",
  "Namespace": "::ara::ifc",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "horizontalPosLeftAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "horizontalPosRightAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "distance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "validFlag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "horizontalMovingSpeed",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "verticalPosAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "objClass",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "trackingFlag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "reserved1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reserved2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}