{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/SensorStatusDataType",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "pasSenStsLongRangeFl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSenStsLongRangeFR",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSenStsShortRangeFl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSenStsShortRangeFml",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSenStsShortRangeFmr",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSenStsShortRangeFr",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSenStsLongRangeRl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSenStsLongRangeRr",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSenStsShortRangeRl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/Header"
    },
    {
      "Name": "msgRollingCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "pasSenStsShortRangeRml",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSenStsShortRangeRmr",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSenStsShortRangeRr",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasEcuStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasEcuVehStatusReponse",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}