{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/Eps2",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "eps2EpsApaCurrentSystemStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "eps2EpsApaFaultStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "eps2EpsApaSteeringAngleInvalid",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "eps2EpsApaSteeringWheelAngleRes",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "eps2EpsControlStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "eps2TorsionBarTorque",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "eps2TorsionBarTorqueDir",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "eps2TosionBarTorqueValid",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    }
  ],
  "IsPlane": "true"
}