{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeSyncState",
  "Namespace": "::ara::tsync",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "timeSyncState",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/TimeSyncState"
    },
    {
      "Name": "subInfoState",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/SubInfoState"
    }
  ],
  "IsPlane": "true"
}