{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/Ebb1A",
  "Namespace": "::ara::actgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ebbActOutputRodTravel",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "ebbActOutputRodTravelSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebbBcsReqBrkPedalApplied",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebbBcsReqBrkPedalAppliedSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}