{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterServiceInterface/DevmCenterServiceInterface/GetSysPowerOffInfoOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "PowerOffInfoType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/PowerOffInfoType"
    },
    {
      "Name": "Int32",
      "Type": "/HuaweiMDC/StdCppDataType/Int32",
      "Padding": "4"
    }
  ],
  "IsPlane": "true"
}