{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/DeviceInfo",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "deviceName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "deviceId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "deviceType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "softVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "hwVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "chipType",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "chipName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}