{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Gw3A",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "gwVehicleModeBroadcast",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "gwOtaDuration",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "true"
}