{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/Frm1",
  "Namespace": "::ara::chassischeryjx65sub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "frm1AccAccEcgpOvrd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frm1AccModeEsp",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "frm1AccTarAcc",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "frm1BrakePreferred",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "frm1ComfortAccLowerValue",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "frm1ComfortAccUpperValue",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "frm1DecToStop",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frm1DriveOff",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frm1HbaLevel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frm1HbaRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frm1LimitAccLowerValue",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "frm1LimitAccUpperValue",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "frm1PrefillRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frm1VlcShutdownMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    }
  ],
  "IsPlane": "true"
}