{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/ObstaclesInfoDataType",
  "Namespace": "::mdc::obstacles",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssComMsgDataType/Header"
    },
    {
      "Name": "msgRollingCounter1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "msgRollingCounter2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "msgRollingCounter3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "msgRollingCounter4",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "obstacleList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/ObstaclesInfoVec"
    },
    {
      "Name": "reserveMsg1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reserveMsg2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "false"
}