{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/MsgDataType/SomeipMsgDataType/Raw180DataImu",
  "Namespace": "::sensor::ins180::imu",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "accelX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "accelY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "accelZ",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "gyroX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "gyroY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "gyroZ",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "imuVaild",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "imuStatus",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean",
      "Padding": "2"
    },
    {
      "Name": "accBiasX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "accBiasY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "accBiasZ",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "gyroBiasX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "gyroBiasY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "gyroBiasZ",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "biasValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean",
      "Padding": "3"
    },
    {
      "Name": "imuTow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "imuWeek",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "2"
    },
    {
      "Name": "imuSyncTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "imuSyncStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "7"
    }
  ],
  "IsPlane": "true"
}