{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Vcu21A",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "vcuEmsAccPedalActPst",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vcuEmsAccPedalActPstVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vcuEmsBrkPedalSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vcuEmsBrkPedalStVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "vcuEmsEngSpd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "vcuEmsEngSpdVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}