{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/ActCompensationMsg",
  "Namespace": "::ara::actcompensation",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "status",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/StatusInfo"
    },
    {
      "Name": "sensor",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/SensorInfo"
    },
    {
      "Name": "gear",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/GearInfo"
    },
    {
      "Name": "brake",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/BrakeInfo"
    },
    {
      "Name": "steer",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/SteerInfo"
    },
    {
      "Name": "egoMotion",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/VehicleMotion"
    },
    {
      "Name": "offset",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/OffsetInfo"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/ActCommonHeader"
    }
  ],
  "IsPlane": "false"
}