{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcu300FCtrlServiceInterface/DevmMcu300FCtrlSomeipServiceInterface/GetMcuVersionOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "VersionResultType",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlMsgDataTypes/DataTypes/VersionResultType"
    },
    {
      "Name": "VersionResultType",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlMsgDataTypes/DataTypes/VersionResultType"
    }
  ],
  "IsPlane": "false"
}