{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwIcm1",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "icm1DisplayVehicleSpeed",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "icm1LdwlkaLaneAssitTypeReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "icm1TotalOdometerKm",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}