{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwHvac3I",
  "Namespace": "::ara::chassisgaca13ican",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "hvacRawExterTemp",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "hvacRawExterTempVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}