{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/PepsSwitch",
  "Namespace": "::ara::body9000",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "pepsSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pepsSwitchUnLock",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pepsSwitchPackIn",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pepsSwitchPackOut",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pepsSwitchTrunkOpen",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pepsSwitchTrunkClose",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pepsSwitchRemoteStart",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}