{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/McuMntClientServiceInterface/McuMntClientServiceInterface/RequestCmdResultsOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "BufArray256",
      "Type": "/HuaweiMDC/MdcPlatformServices/McuMntMsgDataType/DataTypes/BufArray256"
    },
    {
      "Name": "uint32_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    }
  ],
  "IsPlane": "false"
}