{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Vcu14A",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "emsAccButtInfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "emsGasPedalActPstforMrr",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "emsGasPedalActPstforMrrvd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vcuAccDriverOrvd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vcuAccElecEcFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vcuAccTmcFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "vcuVehWheelTorqMax",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "2"
    }
  ],
  "IsPlane": "true"
}