{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/ChassisCheryJx65StatusMsg",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "absEsp1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp1"
    },
    {
      "Name": "absEsp3",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp3"
    },
    {
      "Name": "absEsp4",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp4"
    },
    {
      "Name": "absEsp5",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp5"
    },
    {
      "Name": "absEsp6",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp6"
    },
    {
      "Name": "absEsp7",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp7"
    },
    {
      "Name": "cgwBcm1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwBcm1"
    },
    {
      "Name": "cgwBcm3",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwBcm3"
    },
    {
      "Name": "cgwEms1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwEms1"
    },
    {
      "Name": "cgwEms2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwEms2"
    },
    {
      "Name": "cgwEms3",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwEms3"
    },
    {
      "Name": "cgwIcm1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwIcm1"
    },
    {
      "Name": "cgwIcm2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwIcm2"
    },
    {
      "Name": "cgwIcm5",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwIcm5"
    },
    {
      "Name": "cgwRrm7",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwRrm7"
    },
    {
      "Name": "cgwRrm8",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwRrm8"
    },
    {
      "Name": "cgwRrm9",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwRrm9"
    },
    {
      "Name": "cgwTcu2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwTcu2"
    },
    {
      "Name": "epbG",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/EpbG"
    },
    {
      "Name": "eps1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/Eps1"
    },
    {
      "Name": "eps2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/Eps2"
    },
    {
      "Name": "mfs2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/Mfs2"
    },
    {
      "Name": "sam1G",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/Sam1G"
    },
    {
      "Name": "yas1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/Yas1"
    },
    {
      "Name": "yas2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/Yas2"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/ChassisStatusHeader"
    }
  ],
  "IsPlane": "false"
}