{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/McuMsgDataType/DataTypes/NcsServerDataResponse",
  "Namespace": "::mdc::mcu",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "operationCode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "responeResult",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dataBuf",
      "Type": "/HuaweiMDC/MdcPlatformServices/McuMsgDataType/DataTypes/NcsChannelBuf"
    }
  ],
  "IsPlane": "false"
}