{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/AvmApa2",
  "Namespace": "::ara::chassischeryjx65sub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "apa2AllowEspControlBrake",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apa2EspControlRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "apa2EspSpeedLimitation",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "apa2EspStopDistance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "apa2EspTargetGearRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apa2FailureBrakeMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}