{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcu300FCtrlServiceInterface/DevmMcu300FCtrlSomeipServiceInterface/GetMcuTaskListOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "UInt32",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "TaskListResultType",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlMsgDataTypes/DataTypes/TaskListResultType"
    }
  ],
  "IsPlane": "false"
}