{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/ChassisRepBakUpMsg",
  "Namespace": "::ara::chass::repbakup",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "velocity",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "brake",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/BrakeInfo"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/ChassisRepBakUpHeader"
    }
  ],
  "IsPlane": "false"
}