{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/ChassisCheryJx65CommandMsg",
  "Namespace": "::ara::chassischeryjx65sub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "avmApa1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/AvmApa1"
    },
    {
      "Name": "avmApa2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/AvmApa2"
    },
    {
      "Name": "fcm1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/Fcm1"
    },
    {
      "Name": "fcm2Fws2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/Fcm2Fws2"
    },
    {
      "Name": "frm1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/Frm1"
    },
    {
      "Name": "frm2",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/Frm2"
    },
    {
      "Name": "frm3Fws3",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/Frm3Fws3"
    },
    {
      "Name": "nMmApaAvm",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/NMmApaAvm"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/ChassisCommandHeader"
    }
  ],
  "IsPlane": "false"
}