{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/VehicleMotion",
  "Namespace": "::mdc::ssm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "vx",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "vy",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "vz",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "ax",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "ay",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "az",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "yaw",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "pitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "roll",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "yawRate",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "pitchRate",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "rollRate",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "yawAcceleration",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "pitchAcceleration",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    },
    {
      "Name": "rollAcceleration",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Float32WithValid"
    }
  ],
  "IsPlane": "true"
}