{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/CanFwdMsgDataType/Header",
  "Namespace": "::ara::intfcanfwd",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/CanFwdMsgDataType/Time"
    },
    {
      "Name": "frameId",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}