{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/CanTpMsgDataType/CanTpMsg",
  "Namespace": "::ara::cantp",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/CanTpMsgDataType/CanTpHeader"
    },
    {
      "Name": "data",
      "Type": "/HuaweiMDC/PlatformServiceInterface/CanTpMsgDataType/VectorUint8"
    }
  ],
  "IsPlane": "false"
}