{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/Bcs2A",
  "Namespace": "::ara::actgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "bcsAbsActiveSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsAbsFaultSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsEbdActiveSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsEbdFaultSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsEngTorqDecActiveStFa",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsEngTorqIncActiveSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsTcsActiveSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsTcsFaultSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsVdcActiveSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsVdcFaultSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "bcsVehSpd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "bcsVehSpdVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}