{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/LicmServiceInterface/LicmServiceInterface/GetLicenseInfoOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "GetStateResultType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/LicmMsgDataType/DataTypes/GetStateResultType"
    },
    {
      "Name": "LicDetailInfoType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/LicmMsgDataType/DataTypes/LicDetailInfoType"
    }
  ],
  "IsPlane": "false"
}