{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcu300FConfigTranServiceInterface/DevmMcu300FUpgradeSomeipServiceInterface/GetSwProcessProgressOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "int8_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int8_t"
    },
    {
      "Name": "uint8_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    }
  ],
  "IsPlane": "true"
}