{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncMeasureMsgDataTypes/DataTypes/MeasureData",
  "Namespace": "::ara::tsync",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/GnssInfoDataType/Header"
    },
    {
      "Name": "isPpsValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "gprmcSeconds",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "ppsOsClock",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    }
  ],
  "IsPlane": "false"
}