{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/MsgDataType/SomeipMsgDataType/GacDataInsStatus",
  "Namespace": "::sensor::insgac::insstatus",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "insPosIniSta",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "insVelIniSta",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "insHeadingIniSta",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "insAttitudeIniSta",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "insInsIniSta",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "insWhlspdfusionStatus",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "insStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "true"
}