{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/BcsNm",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "bcsNmDataField1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "bcsNmDataField2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "bcsNmNodeAddress",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsNmWakeupOrignin",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsSubNetWakeRq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}