{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/SafetyStatus",
  "Namespace": "::ara::body9000",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "safeBeltDriverStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "safeBeltPassengerFrStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "safeBeltPassengerRlStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "safeBeltPassengerRmStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "safeBeltPassengerRrStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "driverSeatStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "passengerSeatrFrStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "passengerSeatrRlStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "passengerSeatrRmStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "passengerSeatrRrStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "collisionEvent",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/BodyReportUint8WithValid"
    }
  ],
  "IsPlane": "true"
}