{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/CameraMsgDataType/CameraPublishImageDataStruct",
  "Namespace": "::ara::camera",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "version",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "head",
      "Type": "/HuaweiMDC/StdCppDataType/rawBuffer"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/PlatformServiceInterface/CameraMsgDataType/Uint32Vector"
    }
  ],
  "IsPlane": "false"
}