{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActGacAssembleForDrivingSubDataType/ActGacAssembleForDrivingMsg",
  "Namespace": "::ara::actgacassemblefordriving",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/ActCommonHeader"
    },
    {
      "Name": "turnningLightRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcLcSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adasAccSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adasIcaSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adasNdaSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fHandsoff",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "handsOnDetSource",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "handsOffDetSysInvalid",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "handsoffTimerMs",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "ndaRequestActivesafetyOff",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "ndaRequestActivesafetyOn",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "ndaRequestActivesafetyInhibit",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "mrriAccSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcIcmadasWarnText",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcIcmWarnCardSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcIcmPromptWarn",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcAcuVoiceWarn",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ilcEnableSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ifcTsrAudioWarnEnable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adasNdaEnableSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adasNdalcStyleSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcNdaVoicePromptType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcIcmadasFailureText",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcSpeedLimitIcon",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcSpeedLimitIconSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcNdaStateIcon",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcIcaIconColor",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcNdaIconColor",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcIcandaIconAngle",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "adcAccIconColor",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcCruiseTargetSpeedCard",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "safebeltVibrationReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "safebeltVibrationLevel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "safebeltTightenReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "safebeltTightenLevel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcVibIntensity",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcDriverFaceWindReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcHvacCtrlReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcFlashReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcPositionLampReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "steerWheLightReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "steerWheLightColor",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brakeLightRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adasEcallRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcCcuReqVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcDoorsUnlockReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcDoorsLockReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcWindowOpenReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcWindowCloseReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcPlgmOpenReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcPlgmCloseReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcRearMirrorFoldReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcRearMirrorUnFoldReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcfDemistReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcrDemistReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcfWiperReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcrWiperReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcfWaterSprayReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adcrWaterSprayReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hornReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adasEpbRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reserved",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActGacAssembleForDrivingSubDataType/Array54"
    }
  ],
  "IsPlane": "false"
}