{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/NrmcMsgDataTypes/IntfSpeedInfoObj",
  "Namespace": "::mdc::nrm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ratedSpeed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    },
    {
      "Name": "realRxSpeed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "realTxSpeed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "intfName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "intfIdx",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    }
  ],
  "IsPlane": "false"
}