{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/UartChannelElemType",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "baudRate",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "packageInfo",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/PackageInfoTypeList"
    }
  ],
  "IsPlane": "false"
}