{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwBcm2A",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "bcmAtwsSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmAutoHighBeamCtrlSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmBeamSwitchSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmBonnetAjarSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmBrakeLightSwitchSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmDriverDoorAjarSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmDriverDoorLockSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmFrontFogLampSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmFrontWasherSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmFrontWiperSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmHighBeamSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmKeySt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmLeftTurnLampFaultSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmLeftTurnLampSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmLowBeamSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmMainLampSwSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmParkingLampSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmPsngrDoorAjarSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmPsngrDoorLockSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmRearFogLampSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmReverseSwitchSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmReverseSwitchStVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmRightTurnLampFaultSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmRightTurnLampSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmRlDoorAjarSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmRrDoorAjarSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmTrunkAjarSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmTurnLightSwitchSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmVehReverseSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}