{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/TyreStatus",
  "Namespace": "::mdc::ssm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "tyrePressureValue",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "tyrePressureLeakageStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Uint8WithValid"
    },
    {
      "Name": "tyrePressureTirePStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Uint8WithValid"
    }
  ],
  "IsPlane": "true"
}