{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/CameraInternalDataMethodMsgDataType/CameraInternalData",
  "Namespace": "::ara::camera",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "isValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "data",
      "Type": "/HuaweiMDC/ApplicationDataType/Uint8Vector"
    },
    {
      "Name": "moduleInfo",
      "Type": "/HuaweiMDC/PlatformServiceInterface/CameraInternalDataMethodMsgDataType/ModuleInfo"
    }
  ],
  "IsPlane": "false"
}