{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncDpStatusMsgTypes/DataTypes/StatusType",
  "Namespace": "::ara::tsync::monitor",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "NORMAL",
      "Value": "0"
    },
    {
      "Label": "LOW_POWER_SUSPEND",
      "Value": "1"
    },
    {
      "Label": "LOW_POWER_RESUME",
      "Value": "2"
    }
  ]
}