{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/FaultDmData",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "eventId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "totalSize",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "dataType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "actionTag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "actionInfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "freezeFrameTag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "freezeFrameInfo",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/DidInfoList"
    }
  ],
  "IsPlane": "false"
}