{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/MsgDataType/SomeipMsgDataType/Raw100DataGnss",
  "Namespace": "::sensor::ins100::gnss",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "gnssLat",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssLon",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssAlt",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssVelE",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssVelN",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssVelU",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssAziTrack",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssSpeed",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssRtkStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "gnssStaNum",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "6"
    },
    {
      "Name": "pvtHdop",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "pvtRtkAge",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssSecInGpsWeek",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssGpsWeek",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "6"
    },
    {
      "Name": "gnssUtcTime",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "stdPe",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "stdPn",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "stdPu",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "stdVe",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "stdVn",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "stdVu",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "pDop",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "vDop",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "fixType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "7"
    },
    {
      "Name": "altMsl",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "gnssTimesynSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "6"
    },
    {
      "Name": "gnssTimestampUs",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gnssCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "2"
    },
    {
      "Name": "gnssDataCrc32",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}