{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/ActTimePoint",
  "Namespace": "::ara::actgac",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "year",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "month",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "day",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hour",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "minute",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "second",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "confidence",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}