{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/ObstaclesInfo",
  "Namespace": "::mdc::obstacles",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "objType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "objConfidence",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "objHeight",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "objHeightConfidence",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "objStartX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "objStartY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "objStartStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "objStartAlpha",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "objEndX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "objEndY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "objEndStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "objEndAlpha",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "objTimeStamp",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "reserveMsg1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "reserveMsg2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}