{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/CameraMsgDataType/CameraHeaderStruct",
  "Namespace": "::ara::camera",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "Seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "Stamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/CameraMsgDataType/CameraHeadTimeStruct"
    },
    {
      "Name": "FrameId",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}