{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/DiagInfoList",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ussNumber",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "pasSonarCtrlBusFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSonarRingingTimeFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSonarShortToGnd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSonarPowerVoltLow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSonarPowerVoltHigh",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSonarShortToPositivePole",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasSonarTypeMismatch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}