{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwSbm10bI",
  "Namespace": "::ara::chassisgaca13ican",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "sbmForRpaFailReason",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sbmPhoneBatt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sbmRpAmode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sbmRpaCheckReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sbmRpaDeviceFailReason",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sbmRpaDeviceSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sbmRpaDirectionSel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sbmRpaKeyPstSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}