{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/ResultCode",
  "Namespace": "::mdc::devm",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "kOk",
      "Value": "0"
    },
    {
      "Label": "kError",
      "Value": "1"
    },
    {
      "Label": "kUnsupport",
      "Value": "2"
    },
    {
      "Label": "kUnkonw",
      "Value": "3"
    }
  ]
}