{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/RadarCrFunctionStateSubDataType/RadarCrHeader",
  "Namespace": "::ara::radarcrfunctionstate",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/RadarCrFunctionStateSubDataType/RadarCrStamp"
    },
    {
      "Name": "frame_id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}