{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncGnssMsgDataTypes/DataTypes/GnssStruct",
  "Namespace": "::ara::tsync",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/GnssInfoDataType/Header"
    },
    {
      "Name": "gnssTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "gnssTimeStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "leapSecondType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}