{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/Float32WithValid",
  "Namespace": "::ara::chass::repbakup",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "value",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "confidence",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}