{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/RadarDetectMsgDataType/RadarDetect",
  "Namespace": "::ara::rdetect",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "idPair",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "coordinate",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vx",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vy",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "rcs",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "snr",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "xRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "yRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "zRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vxRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vyRms",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "xQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "yQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "zQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vxQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vyQuality",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "existProbability",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "falseProbability",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "movProperty",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "invalidState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ambiguity",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}