{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCommandMsgDataType/ChassisHeader",
  "Namespace": "::ara::chass::command",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCommandMsgDataType/ChassisTime"
    },
    {
      "Name": "frame_id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}