{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/IfcNm",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ifcNmDataField",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "ifcNmWakeupOrigin",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ifcNodeAddress",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "6"
    }
  ],
  "IsPlane": "true"
}