{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwAcu1aA",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "acuErFuncCfg",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsAdjParkPosCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsErEnterCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsErQuitConfirm",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsScreenCoordX",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "acuPcsScreenCoordY",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "acuPcsScreenTouchSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsSvmFunctionCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsSvmModCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsSvmPgsCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsSvmPgsReturnCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsSvmSingleViewCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsSvmSoundReminderCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuPcsSvmViewModeCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}