{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcu300FConfigTranServiceInterface/DevmMcu300FUpgradeSomeipServiceInterface/GetStateOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "uint32_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    },
    {
      "Name": "uint8_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}