{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssPasMsgDataType/VehicleInfo",
  "Namespace": "::mdc::pasparkslots",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "coordinateX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "coordinateY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "resetFlag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "carAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "vehicletimeStamp",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "workStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "curvature",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "driveDistance",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float",
      "Padding": "4"
    }
  ],
  "IsPlane": "true"
}