{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/SensorInfo",
  "Namespace": "::ara::actgac",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "insideTemperature",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    },
    {
      "Name": "outsideTemperature",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    },
    {
      "Name": "outsideRawTemperature",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    },
    {
      "Name": "relativeHumidity",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Uint16WithValid"
    },
    {
      "Name": "rainLightSensor",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Uint8WithValid"
    },
    {
      "Name": "rainfall",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Uint8WithValid"
    },
    {
      "Name": "timePoint",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/ActTimePoint"
    }
  ],
  "IsPlane": "true"
}