{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Bcs5A",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "bcsFlWheelSpdEdgesSum",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "bcsFlWheelSpdEdgesSumVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "bcsFrWheelSpdEdgesSum",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "bcsFrWheelSpdEdgesSumVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "bcsRlWheelSpdEdgesSum",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "bcsRlWheelSpdEdgesSumVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "bcsRrWheelSpdEdgesSum",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "bcsRrWheelSpdEdgesSumVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}