{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/RmCenterServiceInterface/RmCenterServiceInterface/GetGeaCpuLoadRateOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "Int32Array",
      "Type": "/HuaweiMDC/ApplicationDataType/Int32Array"
    },
    {
      "Name": "UInt32",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "Int8",
      "Type": "/HuaweiMDC/StdCppDataType/Int8"
    }
  ],
  "IsPlane": "false"
}