{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VoConfigDataType/ChnInfo",
  "Namespace": "::mdc::vo",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "slotId",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VoConfigDataType/SlotId"
    },
    {
      "Name": "dsiId",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "isEnabled",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "chnType",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "width",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    },
    {
      "Name": "height",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    },
    {
      "Name": "frameRate",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}