{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/LicmMsgDataType/DataTypes/LicDetailInfoType",
  "Namespace": "::mdc::license",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "status",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "esn",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "bSubInfo",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "subInfo",
      "Type": "/HuaweiMDC/PlatformServiceInterface/LicmMsgDataType/DataTypes/LicSubInfoType"
    }
  ],
  "IsPlane": "false"
}