{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/Sas1",
  "Namespace": "::ara::actgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "sasCalibratedSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "sasSteeringAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "sasSteeringAngleSpd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "sasSteeringAngleVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sasTrimmingStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}