{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/ModeSwitch",
  "Namespace": "::ara::body9000",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "autoDriveSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "emergencySwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apaSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lkaSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "speedLimitSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "accSwitchOnOff",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "accSwitchResume",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "accSwitchCancel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "accSwitchSpeedInc",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "accSwitchSpeedDec",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "accSwitchGapInc",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "accSwitchGapDec",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "switchAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}