{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/Fcm2Fws2",
  "Namespace": "::ara::chassischeryjx65sub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "fcm2AdasTakeoverReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2CameraTextinfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2HmaHighbeamReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2HmaOnOffsts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2HmaStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2LdwlkaLaneAssitfeedback",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2LdwLkaLeftVisualization",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2LdwLkaRightVisualization",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2LdwlkaSensitivityfeedback",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2LdwLkaStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2LdwOnOffSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2SlaOnOffsts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2SlaSpdlimit",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "fcm2SlaSpdlimitWarning",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2SlaState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2TjaIcaMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2TjaIcaOnOffSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fcm2TjaIcaTextinfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}