{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwIcmHvacA",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "hvacCorrectedExterTemp",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "hvacCorrectedExterTempVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "icmDisFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "icmTotalOdometer",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "icmVehInsSpd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "icmqDashAccFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    }
  ],
  "IsPlane": "true"
}