{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/ChassisGacA13IcanStatusMsg",
  "Namespace": "::ara::chassisgaca13ican",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "gwDcm1I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwDcm1I"
    },
    {
      "Name": "gwAcu22bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwAcu22bI"
    },
    {
      "Name": "gwFcp5I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwFcp5I"
    },
    {
      "Name": "gwSbm1I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwSbm1I"
    },
    {
      "Name": "gwAcu10abI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwAcu10abI"
    },
    {
      "Name": "gwTel11bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwTel11bI"
    },
    {
      "Name": "gwIcmHvacI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwIcmHvacI"
    },
    {
      "Name": "gwBcm2I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwBcm2I"
    },
    {
      "Name": "gwBcmRls1bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwBcmRls1bI"
    },
    {
      "Name": "gwAcu23bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwAcu23bI"
    },
    {
      "Name": "gwSbm15bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwSbm15bI"
    },
    {
      "Name": "gwSbm14bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwSbm14bI"
    },
    {
      "Name": "gwBcm1I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwBcm1I"
    },
    {
      "Name": "gwPeps1I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwPeps1I"
    },
    {
      "Name": "gwHvac3I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwHvac3I"
    },
    {
      "Name": "gwTel15bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwTel15bI"
    },
    {
      "Name": "gwAcu6bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwAcu6bI"
    },
    {
      "Name": "gwPeps6I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwPeps6I"
    },
    {
      "Name": "gwTel3bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwTel3bI"
    },
    {
      "Name": "gwSbm10bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwSbm10bI"
    },
    {
      "Name": "gwDms1I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwDms1I"
    },
    {
      "Name": "gwTelRmtCntrlReq1bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwTelRmtCntrlReq1bI"
    },
    {
      "Name": "gwSbmRemoteControlReq1bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwSbmRemoteControlReq1bI"
    },
    {
      "Name": "gwSbm11bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwSbm11bI"
    },
    {
      "Name": "gwAcu12bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwAcu12bI"
    },
    {
      "Name": "gwTel10bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwTel10bI"
    },
    {
      "Name": "gwVcu1I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwVcu1I"
    },
    {
      "Name": "gwAcu29bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwAcu29bI"
    },
    {
      "Name": "gwAcuHvsm2bI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwAcuHvsm2bI"
    },
    {
      "Name": "vcuNmIcan",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/VcuNmIcan"
    },
    {
      "Name": "gwmNmIcan",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwmNmIcan"
    },
    {
      "Name": "gwAcu11abI",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwAcu11abI"
    },
    {
      "Name": "gwEcan1I",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwEcan1I"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/ActCommonHeader"
    }
  ],
  "IsPlane": "false"
}