{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/IfcGacPathSubDataType/PathInfo",
  "Namespace": "::ara::ifcgacpath",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "adcPathpointX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "adcPathpointY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "adcPathpointZ",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "adcPathpointTheta",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "adcPathpointK",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "adcPathpointSpeed",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "adcPathpointAcceleration",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "adcPathpointValid",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "2"
    }
  ],
  "IsPlane": "true"
}