{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationMsgDataType/WheelSpeedInfo",
  "Namespace": "::ara::actcompensation",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "wheelSpeedMps",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "wheelCount",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "wheelDirection",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "wheelSpeedMpsValid",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "wheelCountValid",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "wheelDirectionValid",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}