{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwPeps6I",
  "Namespace": "::ara::chassisgaca13ican",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "pepsApuQuitReason",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pepsSatoQuitReason",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pepsWalQuitReason",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pepsWelQuitReason",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}