{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeSpec",
  "Namespace": "::ara::tsync",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "sec",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int64_t"
    },
    {
      "Name": "nsec",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "subInfoState",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/SubInfoState",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}