{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/FaultPhmData",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "faultSate",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "systemDamageLevel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "faultDesc",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "faultId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "false"
}