{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/LightSwitch",
  "Namespace": "::mdc::ssm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "turnLightSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hazardLightSwicth",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "positionLightSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "daytimeRunningLightSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "highLowBeamSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fogFrontSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "fogRearSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hornSwitch",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}