{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwAcu6bI",
  "Namespace": "::ara::chassisgaca13ican",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "acuAltitudeDecimal",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "acuAltitudeInteger",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "acuAzimuthInfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "acuGpsSignalSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}