{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/InsGsvMsgDataType/GsvInfo",
  "Namespace": "::mdc::gsv",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/GnssInfoDataType/Header"
    },
    {
      "Name": "num",
      "Type": "/HuaweiMDC/StdCppDataType/Int16"
    },
    {
      "Name": "satelliteInfoVec",
      "Type": "/HuaweiMDC/PlatformServiceInterface/InsGsvMsgDataType/SatelliteInfoVec"
    }
  ],
  "IsPlane": "false"
}