{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/ConfigServerMsgDataType/ImplementationDataTypes/ParamUpdateData",
  "Namespace": "::mdc::config::server",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "paramName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "paramValue",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "paramType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "clientName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}