{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/ProbEchoInfo",
  "Namespace": "::mdc::probdistances",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "traceId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "codeId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "distance",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "width",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "high",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "confidence",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "timestamp",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}