{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwTel3eA",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "telTimeDay",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "telTimeHour",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "telTimeMin",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "telTimeMonth",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "telTimeSec",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "telTimeVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "telTimeYear",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "true"
}