{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/BodyReport9000Msg",
  "Namespace": "::ara::body9000",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "lightSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/LightSwitch"
    },
    {
      "Name": "modeSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/ModeSwitch"
    },
    {
      "Name": "mirrorSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/MirrorSwitch"
    },
    {
      "Name": "wiperFrontSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/Wiper"
    },
    {
      "Name": "wiperRearSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/Wiper"
    },
    {
      "Name": "wiperFrontStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/Wiper"
    },
    {
      "Name": "wiperRearStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/Wiper"
    },
    {
      "Name": "padSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/PadSwitch"
    },
    {
      "Name": "lightStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/LightStatus"
    },
    {
      "Name": "doorStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/DoorStatus"
    },
    {
      "Name": "doorSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/DoorSwitch"
    },
    {
      "Name": "windowStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/WindowStatus"
    },
    {
      "Name": "tyreFlStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/TyreStatus"
    },
    {
      "Name": "tyreFrStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/TyreStatus"
    },
    {
      "Name": "tyreRlStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/TyreStatus"
    },
    {
      "Name": "tyreRrStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/TyreStatus"
    },
    {
      "Name": "safetyStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/SafetyStatus"
    },
    {
      "Name": "commonStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/CommonStatus"
    },
    {
      "Name": "pepsSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/PepsSwitch"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/Body9000MsgDataType/BodyReportHeader"
    }
  ],
  "IsPlane": "false"
}