{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeOffsetThreshold",
  "Namespace": "::ara::tsync",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "timeOffsetThreshold",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    },
    {
      "Name": "subInfoState",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/SubInfoState",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}