{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/AbsEsp6",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "esp6LhfWheelDriveDirection",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "esp6LhfWheelSpeedRaw",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "esp6LhfWheelSpeedRawValidData",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp6Qdcacc",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp6RhfWheelDriveDirection",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "esp6RhfWheelSpeedRaw",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "esp6RhfWheelSpeedRawValidData",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "esp6VlcFail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "esp6WheelBrakeForce",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}