{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/MsgDataType/SomeipMsgDataType/Raw180DataImuParaExt",
  "Namespace": "::sensor::ins180::imuparaext",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "extrinsicRoll",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "extrinsicPitch",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "extrinsicYaw",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "extrinsicValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean",
      "Padding": "3"
    },
    {
      "Name": "extrinsicTow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "extrinsicWeek",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "2"
    },
    {
      "Name": "extrinsicSyncTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "extrinsicSyncStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "7"
    }
  ],
  "IsPlane": "true"
}