{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/MsgDataType/SomeipMsgDataType/BydDataIns",
  "Namespace": "::sensor::insbyd::ins",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "insUtcTime",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insGnssSatNum",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "7"
    },
    {
      "Name": "insPitchAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insRollAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insHeadingAngle",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insPitchAngleStd",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insRollAngleStd",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insHeadingAngleStd",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insLocatHeight",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insLatitude",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insLongitude",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insGroundSpeed",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insGroundSpdStd",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insStdLat",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insStdLon",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insStdLocatHeight",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insPreciousLvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "insNavStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "insImuCalStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "5"
    },
    {
      "Name": "insTimestamp",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insTimesynSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "insCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "insDataCrc32",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}