{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcu300FConfigTranServiceInterface/DevmMcu300FUpgradeSomeipServiceInterface/GetSwVersionOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "Uint8List",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/Uint8List"
    },
    {
      "Name": "uint8_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    }
  ],
  "IsPlane": "false"
}