{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/CameraControlCommandMethodServiceInterface/CameraControlCommandMethodServiceInterface/CameraControlCommandOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "Uint8Vector",
      "Type": "/HuaweiMDC/ApplicationDataType/Uint8Vector"
    },
    {
      "Name": "Int32",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    }
  ],
  "IsPlane": "false"
}