{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DataType/FlowControlMsg",
  "Namespace": "::ara::dcap",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "gain",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t",
      "IsOptional": "false"
    },
    {
      "Name": "send_enable",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean",
      "IsOptional": "false"
    },
    {
      "Name": "capture_enable",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean",
      "Padding": "2",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "true"
}