{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/RadarMsgDataType/GuardnailInfo",
  "Namespace": "::ara::radar",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "confidence",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "dxStart",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "dxEnd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "guardnailC0",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "guardnailC1",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "guardnailC2",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "guardnailC3",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "reserved1",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "reserved2",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}