{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwHod1A",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "hodApRestStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hodCalibrationSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hodFaultStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hodLinComFault",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hodTouchZone1",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hodTouchZone2",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hodTouchZone3",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hodvBattOorFault",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}