{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/DiagnosisDataType",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "diagInfoList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/DiagnosisVec"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/Header"
    },
    {
      "Name": "pasEcuOverVoltage",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasEcuUnderVoltage",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "pasEcuBusoffError",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "msgRollingCounter",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "false"
}