{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssPasMsgDataType/EchoInfo",
  "Namespace": "::mdc::pasdetectdistances",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "width",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "high",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "confidence",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}