{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/GwAcu2aA",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "acuBsdCfg",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuDowCfg",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuHmaSwitchReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuHwaSwitchReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuHwahfAudioWarningTypeCfg",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuHwahfCfg",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuLdsTypeReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuLdwLkaCfg",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuRaeBcfg",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuRctaCfg",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuTsrAudioWarnReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuTsrSwitchReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acuiAccSwitchReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}