{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13IcanPubDataType/GwBcm1I",
  "Namespace": "::ara::chassisgaca13ican",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "bcmBrakeLightFaultSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmBrakeLightSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmHazardLampSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcmReverseLightSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "tpmsTyreSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}