{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/DidInfoElem",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "did",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "value",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/Uint8List"
    }
  ],
  "IsPlane": "false"
}