{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/Frm2",
  "Namespace": "::ara::chassischeryjx65sub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "frm2AccMinimumBraking",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frm2AccStartStopInfo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "frm2AebDecCtrlRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "frm2AebTarDec",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "frm2AwbLevel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "frm2AwbRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}