{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/ActGacA13AcanStatusMsg",
  "Namespace": "::ara::actgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "sas1",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/Sas1"
    },
    {
      "Name": "bcs3A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/Bcs3A"
    },
    {
      "Name": "bcs8A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/Bcs8A"
    },
    {
      "Name": "bcs2A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/Bcs2A"
    },
    {
      "Name": "ebb1A",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActGacA13AcanPubDataType/Ebb1A"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/ActCommonHeader"
    }
  ],
  "IsPlane": "false"
}