{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/Yas2",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "yas2LongitudinalAcceleration",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "yas2LongitudinalAccelerationSigValidData",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}