{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/SteerInfo",
  "Namespace": "::ara::actgac",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "steerPinionAngle",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    },
    {
      "Name": "steerAngle",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    },
    {
      "Name": "steerAngleRate",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    },
    {
      "Name": "sasSteerAngle",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    },
    {
      "Name": "sasSteerAngleRate",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    },
    {
      "Name": "steerTorque",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/Float32WithValid"
    }
  ],
  "IsPlane": "true"
}