{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/MsgDataType/SomeipMsgDataType/GacDataImu",
  "Namespace": "::sensor::insgac::imu",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "accelX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "accelY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "accelZ",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "gyroX",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "gyroY",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "gyroZ",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "imuVaild",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "imuStatus",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean",
      "Padding": "2"
    },
    {
      "Name": "imuTow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "imuWeek",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "6"
    },
    {
      "Name": "imuSyncTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "imuSyncStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "7"
    }
  ],
  "IsPlane": "true"
}