{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/MsgDataType/SomeipMsgDataType/GacDataIns",
  "Namespace": "::sensor::insgac::ins",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "insGndSpd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insGndSpdStd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insEastSpd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insEastSpdStd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insNorthSpd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insNorthSpdStd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insLocatingHght",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insHghtStd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insLongd",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insLongdStd",
      "Type": "/HuaweiMDC/StdCppDataType/Float",
      "Padding": "4"
    },
    {
      "Name": "insLatd",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "insLatdStd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insYaw",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insYawStd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insPitch",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insPitchStd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insRoll",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insRollStd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "insValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "insDrConfidence",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "insTow",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "insWeek",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "2"
    },
    {
      "Name": "insSyncTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "insSyncStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "7"
    }
  ],
  "IsPlane": "true"
}