{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/UartConfigParam",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "uartChannel",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/UartChannelElemTypeList"
    },
    {
      "Name": "timesyncConfig",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuMsgDataType/DataTypes/TimesyncConfigType"
    }
  ],
  "IsPlane": "false"
}