{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/MacAddressElem",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "subType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "format",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "macBuf",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/BufArray12"
    }
  ],
  "IsPlane": "false"
}