{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncApMsgDataTypes/DataTypes/TsyncStatusFlag",
  "Namespace": "::ara::tsync",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "kTimeOut",
      "Value": "0"
    },
    {
      "Label": "kSynchronized",
      "Value": "1"
    },
    {
      "Label": "kSynchToGateway",
      "Value": "2"
    },
    {
      "Label": "kTimeLeapFuture",
      "Value": "3"
    },
    {
      "Label": "kTimeLeapPast",
      "Value": "4"
    },
    {
      "Label": "kHasDLS",
      "Value": "5"
    },
    {
      "Label": "kDLSActive",
      "Value": "6"
    },
    {
      "Label": "kSynchronizedNow",
      "Value": "16"
    }
  ]
}