{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/UpdateInfo",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "version",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "packgName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "deviceType",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "mainSub",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "versionStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}