{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/LidarRawMsgDataType/LidarRawPointCloud",
  "Namespace": "::ara::lidar",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/LidarMsgDataType/Header"
    },
    {
      "Name": "data",
      "Type": "/HuaweiMDC/PlatformServiceInterface/LidarRawMsgDataType/VectorUint8"
    }
  ],
  "IsPlane": "false"
}