{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65PubDataType/CgwRrm7",
  "Namespace": "::ara::chassischeryjx65pub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "rrm7CurrentTimeDay",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "rrm7CurrentTimeHour",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "rrm7CurrentTimeMinute",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "rrm7CurrentTimeMonth",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rrm7CurrentTimeSecond",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rrm7CurrentTimeYear",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}