{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/BodyReportHeader",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/BodyReportTime"
    },
    {
      "Name": "frame_id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}