{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/UpaDataType",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ussInfoList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/UssVec"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/Header"
    },
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "false"
}