{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Ebb2A",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ebbBrkFxCpb",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebbBrkLightReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "ebbBrkPedPst",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "ebbBrkPedPstVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebbBrkPedalApplied",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "ebbBrkPedalAppliedSt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}