{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/VehicleBodyInfo",
  "Namespace": "::mdc::ssm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "lightSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/LightSwitch"
    },
    {
      "Name": "modeSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/ModeSwitch"
    },
    {
      "Name": "mirrorSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/MirrorSwitch"
    },
    {
      "Name": "wiperFrontSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Wiper"
    },
    {
      "Name": "wiperRearSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Wiper"
    },
    {
      "Name": "wiperFrontStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Wiper"
    },
    {
      "Name": "wiperRearStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/Wiper"
    },
    {
      "Name": "padSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/PadSwitch"
    },
    {
      "Name": "lightStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/LightStatus"
    },
    {
      "Name": "doorStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/DoorStatus"
    },
    {
      "Name": "doorSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/DoorSwitch"
    },
    {
      "Name": "windowStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/WindowStatus"
    },
    {
      "Name": "tyreFlStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/TyreStatus"
    },
    {
      "Name": "tyreFrStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/TyreStatus"
    },
    {
      "Name": "tyreRlStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/TyreStatus"
    },
    {
      "Name": "tyreRrStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/TyreStatus"
    },
    {
      "Name": "safetyStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/SafetyStatus"
    },
    {
      "Name": "commonStatus",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/CommonStatus"
    },
    {
      "Name": "pepsSwitch",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VehicleInfoMsgDataType/PepsSwitch"
    }
  ],
  "IsPlane": "false"
}