{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/ChassisRepBakUpHeader",
  "Namespace": "::ara::chass::repbakup",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisRepBakUpMsgDataType/ChassisRepBakUpTime"
    },
    {
      "Name": "frame_id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}