{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCommandMsgDataType/RedCmd",
  "Namespace": "::ara::chass::command",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "comfortBoundaryValid",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "longAccelerationState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "longControlMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "motTypeReqMode",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "secureReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "shutdownReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "suprAvail",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "comfortBoundaryUp",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "comfortBoundaryLow",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "jerkMax",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "jerkMin",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "longAccelerationCmd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}