{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/ChassisCommandHeader",
  "Namespace": "::ara::chassischeryjx65sub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/ChassisCommandStamp"
    },
    {
      "Name": "frame_id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}