{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Bcs10A",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "bcsCddapVehHoldActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsLsM12ComfortAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsLsM12EmergencyAvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsLsM23Avl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsLsmPosLongaCapbl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsLsmSubMtLevelEcho",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsLsmSubMtLongEcho",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsLsmSubMtReqAvailable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsLsmSubMtReqEcho",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsRlWheelRotatedDirection",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsRlWheelRotatedDirectionApa",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsRlWheelRotatedDirectionVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsRlWheelSpd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "bcsRlWheelSpdVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsRrWheelRotatedDirection",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsRrWheelRotatedDirectionApa",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsRrWheelRotatedDirectionVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsRrWheelSpd",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "bcsRrWheelSpdVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}