{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/DistanceDataType",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "distanceInfoList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/DistanceVec"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UssMsgDataType/Header"
    },
    {
      "Name": "msgRollingCounterFront",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "msgRollingCounterRear",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "false"
}