{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/TsycNodeInfo",
  "Namespace": "::ara::tsync",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "nodeName",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeName"
    },
    {
      "Name": "timeSource",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/ManagerPlaneTimeSource",
      "Padding": "5"
    },
    {
      "Name": "mpTimeSpec",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeSpec"
    },
    {
      "Name": "mpTimeSyncState",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeSyncState"
    },
    {
      "Name": "dpTimeSyncState",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeSyncState"
    },
    {
      "Name": "mpUnsyncTimes",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeUnsyncTimes"
    },
    {
      "Name": "dpUnsyncTimes",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeUnsyncTimes",
      "Padding": "4"
    },
    {
      "Name": "mpTimeOffset",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeOffset"
    },
    {
      "Name": "dpTimeOffset",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeOffset"
    },
    {
      "Name": "mpTimeOffsetThreshold",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeOffsetThreshold"
    },
    {
      "Name": "dpTimeOffsetThreshold",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeOffsetThreshold"
    },
    {
      "Name": "dpTimeSpec",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeSpec"
    }
  ],
  "IsPlane": "true"
}