{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/VersionISP",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "uboot",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "os",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "sys",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "ubootBak",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "osBak",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "sysBak",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}