{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/MsgDataType/CanFdMsgDataSType/CanFdBusDataParamS",
  "Namespace": "::mdc::mdccan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "elementList",
      "Type": "/HuaweiMDC/MdcPlatformServices/MsgDataType/CanFdMsgDataSType/ElementListS"
    }
  ],
  "IsPlane": "false"
}