{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/MacAddress",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "macNum",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "macArray",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/MacAddrArray"
    },
    {
      "Name": "result",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}