{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/IfcGacPathSubDataType/IfcGacPathMsg",
  "Namespace": "::ara::ifcgacpath",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/IfcGacPathSubDataType/IfcGacHeader"
    },
    {
      "Name": "path",
      "Type": "/HuaweiMDC/PlatformServiceInterface/IfcGacPathSubDataType/PathInfoArray"
    }
  ],
  "IsPlane": "false"
}