{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/DmsNm",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "dmsNmDataField",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "dmsNmSourceAddress",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dmsNmWakeupOrigin",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "6"
    }
  ],
  "IsPlane": "true"
}