{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/McuNrmMsgDataType/DataTypes/DcComCtrlChnlConfig",
  "Namespace": "::mdc::mcu",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "chnlId",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "appTx",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "appRx",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "nmTx",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "nmRx",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    }
  ],
  "IsPlane": "true"
}