{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisCheryJx65SubDataType/AvmApa1",
  "Namespace": "::ara::chassischeryjx65sub",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "apa1ApaActive",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apa1ApaFailureSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "2"
    },
    {
      "Name": "apa1ApaSteeringWheelAngleReq",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "apa1ApaSystemSts",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apa1EpsControlRequest",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "apa1ReasonForDvDnotDisplyApa",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}