{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/ActCompensationGacMsg",
  "Namespace": "::ara::actgac",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "status",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/StatusInfo"
    },
    {
      "Name": "sensor",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/SensorInfo"
    },
    {
      "Name": "gear",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/GearInfo"
    },
    {
      "Name": "brake",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/BrakeInfo"
    },
    {
      "Name": "steer",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/SteerInfo"
    },
    {
      "Name": "egoMotion",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/VehicleMotion"
    },
    {
      "Name": "offset",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/OffsetInfo"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/ActCompensationGacMsgDataType/ActCommonHeader"
    }
  ],
  "IsPlane": "false"
}