{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/BodyCommandMsg",
  "Namespace": "::ara::body",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "source",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "adsFunction",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "adsWorkStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "moduleId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "turnLightCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hazardLightCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "reverseLightCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hornCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "highLowBeamLightCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "dayTimeRunLightCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sidePositionLightCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "windShieldWashCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "windShieldWiperCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rearViewMirrorCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "parkFinishRemind",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "leftFrontWindowCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rightFrontWindowCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "leftRearWindowCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rightRearWindowCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "topWindowCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "turnLightState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hazardLightState",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brakeLightCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brakeLightValid",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hazardLightValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "highLowBeamLighValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "hornValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "leftFrontWindowValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "leftRearWindowValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "rearViewMirrorValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "rightFrontWindowValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "rightRearWindowValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "topWindowValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "turnLightValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "windShieldWashValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "windShieldWiperValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/BodyMsgDataType/BodyCmdHeader"
    },
    {
      "Name": "doorLockCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "turnLightCmdFrequency",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "brakeLightCmdFrequency",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "hazardLightCmdFrequency",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "doorLockCmdValid",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "seatVibrationCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "safeBeltFastenCmd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "openDoorWarningFL",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "openDoorWarningFR",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "openDoorWarningRL",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "openDoorWarningRR",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rearViewMirrorWarningLeft",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rearViewMirrorWarningRight",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}