{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/ChassisGacA13AcanPubDataType/Bcs11A",
  "Namespace": "::ara::chassisgaca13acan",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "bcsActVehLaltrlAccel",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "bcsActVehLaltrlAccelVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "bcsActVehLongAccel",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "bcsActVehLongAccelVd",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsTcsOff",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "bcsVdcOff",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "1"
    },
    {
      "Name": "bcsVehLaltrlAccelOffset",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "bcsVehLongAccelOffset",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}