{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/DevmMcu300FConfigTranServiceInterface/DevmMcu300FConfigTranServiceInterface/GetConfigFileOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "UInt8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "UInt32",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "BufArray512",
      "Type": "/HuaweiMDC/MdcPlatformServices/DevmMcuCtrlMsgDataTypes/DataTypes/BufArray512"
    }
  ],
  "IsPlane": "false"
}