{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/NodeTimeOffset",
  "Namespace": "::ara::tsync",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "timeOffset",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int64_t"
    },
    {
      "Name": "subInfoState",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TsyncMntMsgDataTypes/DataTypes/SubInfoState",
      "Padding": "7"
    }
  ],
  "IsPlane": "true"
}