/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_DO_SOME_IP_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_DO_SOME_IP_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/DoSomeIPStub.hpp>
#include <v1/commonapi/DoSomeIPSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

template <typename _Stub = ::v1::commonapi::DoSomeIPStub, typename... _Stubs>
class DoSomeIPSomeIPStubAdapterInternal
    : public virtual DoSomeIPStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< DoSomeIPSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> DoSomeIPSomeIPStubAdapterHelper;

    ~DoSomeIPSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        DoSomeIPSomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::DoSomeIPStub,
        CommonAPI::Version
    > getDoSomeIPInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::DoSomeIPStub,
        std::tuple< DoSomeIP::DoSomeIPReqUdsMessage>,
        std::tuple< DoSomeIP::stdErrorTypeEnum, DoSomeIP::DoSomeIPRespUdsMessage>,
        std::tuple< ::v1::commonapi::DoSomeIP_::DoSomeIPReqUdsMessageDeployment_t>,
        std::tuple< ::v1::commonapi::DoSomeIP_::stdErrorTypeEnumDeployment_t, ::v1::commonapi::DoSomeIP_::DoSomeIPRespUdsMessageDeployment_t>
    > udsMessageRequestStubDispatcher;
    
    DoSomeIPSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        DoSomeIPSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< DoSomeIPStub>(_stub)),
        getDoSomeIPInterfaceVersionStubDispatcher(&DoSomeIPStub::lockInterfaceVersionAttribute, &DoSomeIPStub::getInterfaceVersion, false, true),
        udsMessageRequestStubDispatcher(
            &DoSomeIPStub::udsMessageRequest,
            false,
            _stub->hasElement(0),
            std::make_tuple(&::v1::commonapi::DoSomeIP_::DoSomeIPReqUdsMessageDeployment),
            std::make_tuple(&::v1::commonapi::DoSomeIP_::stdErrorTypeEnumDeployment, &::v1::commonapi::DoSomeIP_::DoSomeIPRespUdsMessageDeployment))
        
    {
        DoSomeIPSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7530) }, &udsMessageRequestStubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void DoSomeIPSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void DoSomeIPSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::commonapi::DoSomeIPStub, typename... _Stubs>
class DoSomeIPSomeIPStubAdapter
    : public DoSomeIPSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    DoSomeIPSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          DoSomeIPSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_Do_Some_IP_SOMEIP_STUB_ADAPTER_HPP_
