/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_STDTYPE_IMPL_TYPE_INT32_T_H
#define RTF_STDTYPE_IMPL_TYPE_INT32_T_H
#include <cstdint>

namespace rtf {
namespace stdtype {
using int32_t = std::int32_t;
} // namespace stdtype
} // namespace rtf


#endif // RTF_STDTYPE_IMPL_TYPE_INT32_T_H
