/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_STDTYPE_IMPL_TYPE_STRING_H
#define RTF_STDTYPE_IMPL_TYPE_STRING_H
#include "ara/core/string.h"

namespace rtf {
namespace stdtype {
using String = ara::core::String;
} // namespace stdtype
} // namespace rtf


#endif // RTF_STDTYPE_IMPL_TYPE_STRING_H
