/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_STDTYPE_IMPL_TYPE_UINT64_T_H
#define RTF_STDTYPE_IMPL_TYPE_UINT64_T_H
#include <cstdint>

namespace rtf {
namespace stdtype {
using uint64_t = std::uint64_t;
} // namespace stdtype
} // namespace rtf


#endif // RTF_STDTYPE_IMPL_TYPE_UINT64_T_H
