/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_STDTYPE_IMPL_TYPE_BOOLEAN_H
#define RTF_STDTYPE_IMPL_TYPE_BOOLEAN_H

namespace rtf {
namespace stdtype {
using boolean = bool;
} // namespace stdtype
} // namespace rtf


#endif // RTF_STDTYPE_IMPL_TYPE_BOOLEAN_H
