/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_SCHEDULEMODE_H
#define RTF_MAINTAIND_IMPL_TYPE_SCHEDULEMODE_H

#include "rtf/stdtype/impl_type_uint8_t.h"
namespace rtf {
namespace maintaind {
enum class ScheduleMode : rtf::stdtype::uint8_t {
    DETERMINATE,
    INDETERMINATE
};
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_SCHEDULEMODE_H