/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2019. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_HISTORYQOS_H
#define RTF_MAINTAIND_IMPL_TYPE_HISTORYQOS_H

#include "rtf/stdtype/impl_type_uint8_t.h"
namespace rtf {
namespace maintaind {
enum class HistoryQos : rtf::stdtype::uint8_t {
    KEEP_LAST,
    KEEP_ALL
};
}
}

#endif // RTF_MAINTAIND_IMPL_TYPE_HISTORYQOS_H
