/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2023. All rights reserved.
 */

#ifndef HOZONEXECUTABLE_COMMONSENDBASE_EXECUTABLE_H
#define HOZONEXECUTABLE_COMMONSENDBASE_EXECUTABLE_H

#include "ara/adas/adasserviceinterface_skeleton.h"
#include "hozon/hmi2location/hozoninterface_hmi2location_skeleton.h"
#include "hozon/hmi2router/hozoninterface_hmi2router_skeleton.h"
#include "hozon/hmi_planningdec/hozoninterface_planningdecisioninfo_skeleton.h"
#include "hozon/interface/aeb2ego/hozoninterface_aeb2ego_skeleton.h"
#include "hozon/interface/canfdmsg/hozoninterface_canfdmsg_skeleton.h"
#include "hozon/interface/chassis/hozoninterface_chassis_skeleton.h"
#include "hozon/interface/control/hozoninterface_control_skeleton.h"
#include "hozon/interface/debugcontrol/hozoninterface_debugcontrol_skeleton.h"
#include "hozon/interface/debugpb/hozoninterface_debugpb_skeleton.h"
#include "hozon/interface/debugplan/hozoninterface_debugplan_skeleton.h"
#include "hozon/interface/egohmi/hozoninterface_egohmi_skeleton.h"
#include "hozon/interface/freespace/hozoninterface_freespace_skeleton.h"
#include "hozon/interface/gnssinfo/hozoninterface_gnssinfo_skeleton.h"
#include "hozon/interface/imu/hozoninterface_imuinfo_skeleton.h"
#include "hozon/interface/ins/hozoninterface_insinfo_skeleton.h"
#include "hozon/interface/laneline/hozoninterface_laneline_skeleton.h"
#include "hozon/interface/latency_test_1k/hozoninterface_latencytest1k_skeleton.h"
#include "hozon/interface/latency_test_2k/hozoninterface_latencytest2k_skeleton.h"
#include "hozon/interface/latency_test_500b/hozoninterface_latencytest500b_skeleton.h"
#include "hozon/interface/latency_test_5k/hozoninterface_latencytest5k_skeleton.h"
#include "hozon/interface/loc_element/hozoninterface_loc_element_skeleton.h"
#include "hozon/interface/location/hozoninterface_location_skeleton.h"
#include "hozon/interface/location/hozoninterface_locationhdmapinfo_skeleton.h"
#include "hozon/interface/location/hozoninterface_locationmonitor_skeleton.h"
#include "hozon/interface/location/hozoninterface_locationnodeinfo_skeleton.h"
#include "hozon/interface/lowspeedbsd/hozoninterface_low_spd_bsd_skeleton.h"
#include "hozon/interface/mapmsg/hozoninterface_mapmsg_skeleton.h"
#include "hozon/interface/mcu2ego/hozoninterface_mcu2ego_skeleton.h"
#include "hozon/interface/objcamera/hozoninterface_obj_camera_skeleton.h"
#include "hozon/interface/objfusion/hozoninterface_obj_fusion_skeleton.h"
#include "hozon/interface/objlidar/hozoninterface_obj_lidar_skeleton.h"
#include "hozon/interface/objradar/hozoninterface_obj_radar_skeleton.h"
#include "hozon/interface/objsignal/hozoninterface_obj_signal_skeleton.h"
#include "hozon/interface/ocr/hozoninterface_ocr_skeleton.h"
#include "hozon/interface/parkinglot/hozoninterface_parkinglot_skeleton.h"
#include "hozon/interface/perceptioninfo/hozoninterface_perceptioninfo_skeleton.h"
#include "hozon/interface/planning/hozoninterface_planning_skeleton.h"
#include "hozon/interface/pointcloud/hozoninterface_pointcloud_skeleton.h"
#include "hozon/interface/prediction/hozoninterface_prediction_skeleton.h"
#include "hozon/interface/proto/hozoninterface_proto_skeleton.h"
#include "hozon/interface/state_machine/hozoninterface_fieldtest_skeleton.h"
#include "hozon/interface/state_machine/hozoninterface_statemachine_skeleton.h"
#include "hozon/interface/uss/hozoninterface_uss_skeleton.h"
#include "hozon/interface/ussinfo/hozoninterface_ussinfo_skeleton.h"
#include "hozon/soc_mcu/hzsocmcuadasrtfclientserviceinterface_skeleton.h"
#include "hozon/soc_mcu/hzsocmcuclientserviceinterface_skeleton.h"
#include "mdc/cam/camera/cameradecodedmbufserviceinterface_skeleton.h"
#include "mdc/cam/camera/cameraencodedmbufserviceinterface_skeleton.h"
#include "mdc/cam/camera/cameraimagembufserviceinterface_skeleton.h"

#endif // HOZONEXECUTABLE_COMMONSENDBASE_EXECUTABLE_H
