/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Crypto-Generator
 */

#ifndef HZ_CONFIG_SERVER_LOCAL_CRYPTO_PROVIDER_H
#define HZ_CONFIG_SERVER_LOCAL_CRYPTO_PROVIDER_H
#include "ara/core/string_view.h"
namespace ara {
namespace crypto {
    static const ara::core::StringView KMSCryptoProviderID = "bdfa408d-3d4f-41ff-a33e-f65b05388078";
    static const ara::core::StringView SLOT2 = "1d719235-7b23-4fcd-8700-45561768f544";
} // namespace crypto
} // namespace ara
#endif // HZ_CONFIG_SERVER_LOCAL_CRYPTO_PROVIDER_H
