%YAML:1.0

module:
    className: ProtobufSendSample
    path: ./lib/libproto_send_sample.so

recvInstances:
    - name: cm_protobuf
      type: cm_proxy
      topic: /hozon/cm_protobuf
      domainId: 0
sendInstances:
    - name: cm_protobuf
      type: cm_skeleton
      topic: /hozon/cm_protobuf
      domainId: 1

log:
    mode: 3
    file: ./
    name: cmps
    description: cm_proto_sample
    level: 0   
    adf:
      level: 0

# trigger二选一即可
trigger:
    - name: main
      type: PERIOD
      period: 1000
      auxSources:
          - name: cm_protobuf