/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_LATENCYQUERYINFO_H
#define RTF_MAINTAIND_IMPL_TYPE_LATENCYQUERYINFO_H
#include "rtf/stdtype/impl_type_uint16_t.h"
#include "rtf/maintaind/latency/impl_type_latencyindex.h"

namespace rtf {
namespace maintaind {
struct LatencyQueryInfo {
    ::rtf::stdtype::uint16_t windows_;
    ::rtf::maintaind::LatencyIndex latencyIndex_;

    static bool IsPlane() noexcept
    {
        return false;
    }

    using IsEnumerableTag = void;
    template<typename F>
    void enumerate(F& fun) noexcept
    {
        fun(windows_);
        fun(latencyIndex_);
    }

    template<typename F>
    void enumerate(F& fun) const noexcept
    {
        fun(windows_);
        fun(latencyIndex_);
    }

    bool operator == (const ::rtf::maintaind::LatencyQueryInfo& t) const noexcept
    {
        return (windows_ == t.windows_) && (latencyIndex_ == t.latencyIndex_);
    }
};
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_LATENCYQUERYINFO_H
