/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef AVM_SEGMENTATION_LOGGING_BEHAVIOR_H
#define AVM_SEGMENTATION_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // AVM_SEGMENTATION_LOGGING_BEHAVIOR_H
