/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef CAMERATRACKEREXECUTABLE_LOGGING_BEHAVIOR_H
#define CAMERATRACKEREXECUTABLE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // CAMERATRACKEREXECUTABLE_LOGGING_BEHAVIOR_H
