/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef CAMERALANEEXECUTABLE_LOGGING_BEHAVIOR_H
#define CAMERALANEEXECUTABLE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // CAMERALANEEXECUTABLE_LOGGING_BEHAVIOR_H
