/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef CONFIG_CLIENT_LOGGING_BEHAVIOR_H
#define CONFIG_CLIENT_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // CONFIG_CLIENT_LOGGING_BEHAVIOR_H
