/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef DEVM_CLIENT_LOGGING_BEHAVIOR_H
#define DEVM_CLIENT_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // DEVM_CLIENT_LOGGING_BEHAVIOR_H
