/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef EHP_LOGGING_BEHAVIOR_H
#define EHP_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // EHP_LOGGING_BEHAVIOR_H
