/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef FHAT_LOGGING_BEHAVIOR_H
#define FHAT_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // FHAT_LOGGING_BEHAVIOR_H
