/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef FM_LOGGING_BEHAVIOR_H
#define FM_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // FM_LOGGING_BEHAVIOR_H
