/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef LANE_LOGGING_BEHAVIOR_H
#define LANE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // LANE_LOGGING_BEHAVIOR_H
