/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef LIBLIDAR_A_CM_LOGGING_BEHAVIOR_H
#define LIBLIDAR_A_CM_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // LIBLIDAR_A_CM_LOGGING_BEHAVIOR_H
