/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef LPM_CLIENT_LOGGING_BEHAVIOR_H
#define LPM_CLIENT_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // LPM_CLIENT_LOGGING_BEHAVIOR_H
