/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef MVIZ_LIDAR_LOGGING_BEHAVIOR_H
#define MVIZ_LIDAR_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // MVIZ_LIDAR_LOGGING_BEHAVIOR_H
