/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef OBJECT_LOGGING_BEHAVIOR_H
#define OBJECT_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // OBJECT_LOGGING_BEHAVIOR_H
