/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef ROADMARK_LOGGING_BEHAVIOR_H
#define ROADMARK_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // ROADMARK_LOGGING_BEHAVIOR_H
