/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef TLR_LOGGING_BEHAVIOR_H
#define TLR_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // TLR_LOGGING_BEHAVIOR_H
