/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef USS_PERCEPTION_LOGGING_BEHAVIOR_H
#define USS_PERCEPTION_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // USS_PERCEPTION_LOGGING_BEHAVIOR_H
