/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef VEHICLE_DATA_COLLECT_LOGGING_BEHAVIOR_H
#define VEHICLE_DATA_COLLECT_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // VEHICLE_DATA_COLLECT_LOGGING_BEHAVIOR_H
