/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Generated by Log-Generator
 */

#ifndef VISUAL_SLAM_EXECUTE_LOGGING_BEHAVIOR_H
#define VISUAL_SLAM_EXECUTE_LOGGING_BEHAVIOR_H

const bool g_LoggingBehavior = false;

#endif // VISUAL_SLAM_EXECUTE_LOGGING_BEHAVIOR_H
