/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_E2EPROFILE_H
#define RTF_MAINTAIND_IMPL_TYPE_E2EPROFILE_H

#include "rtf/stdtype/impl_type_uint8_t.h"
namespace rtf {
namespace maintaind {
enum class E2EProfile : rtf::stdtype::uint8_t {
    PROFILE04 = 4U,
    PROFILE05 = 5U,
    PROFILE06 = 6U,
    PROFILE07 = 7U,
    PROFILE11 = 11U,
    PROFILE22 = 22U,
    PROFILE4M = 41U,
    PROFILE44 = 44U,
    UNDEFINE = 255U
};
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_E2EPROFILE_H
