/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2021. All rights reserved.
 * Generated by VRTF CM-Generator
 */

#ifndef RTF_MAINTAIND_IMPL_TYPE_EVENTE2ECONFIGINFOVECTOR_H
#define RTF_MAINTAIND_IMPL_TYPE_EVENTE2ECONFIGINFOVECTOR_H
#include "ara/core/vector.h"
#include "rtf/maintaind/e2e/impl_type_evente2econfiginfo.h"

namespace rtf {
namespace maintaind {
using EventE2EConfigInfoVector = ara::core::Vector<rtf::maintaind::EventE2EConfigInfo>;
} // namespace maintaind
} // namespace rtf


#endif // RTF_MAINTAIND_IMPL_TYPE_EVENTE2ECONFIGINFOVECTOR_H
