/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/DoSomeIPSomeIPDeployment.hpp>

namespace v1 {
namespace commonapi {
namespace DoSomeIP_ {

// Type-specific deployments
::v1::commonapi::DoSomeIP_::my_arrayDeployment_t my_arrayDeployment(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr), 0, 100, 4);
TargetAddressTypeDeployment_t TargetAddressTypeDeployment(32, false);
::v1::commonapi::DoSomeIP_::DoSomeIPReqUdsMessageDeployment_t DoSomeIPReqUdsMessageDeployment(0, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), &::v1::commonapi::DoSomeIP_::TargetAddressTypeDeployment, &::v1::commonapi::DoSomeIP_::my_arrayDeployment);
::v1::commonapi::DoSomeIP_::DoSomeIPRespUdsMessageDeployment_t DoSomeIPRespUdsMessageDeployment(0, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), &::v1::commonapi::DoSomeIP_::TargetAddressTypeDeployment, &::v1::commonapi::DoSomeIP_::my_arrayDeployment);
stdErrorTypeEnumDeployment_t stdErrorTypeEnumDeployment(32, false);

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace DoSomeIP_
} // namespace commonapi
} // namespace v1
