#include "common.idl"
#include "type.idl"

struct AlgMcuEgoNNPMsg {
    uint8 LongitudCtrlDecToStopReq;
    uint8 LongitudCtrlDriveOff;
    uint8 DriveOffinhibition;
    uint8 DriveOffinhibitionObjType;
    uint8 Lcsndconfirm;
    uint8 TurnLightReqSt;
    uint8 Lcsndrequest;
    uint8 PayModeConfirm;
    uint8 SpdAdaptComfirm;
    uint8 ALC_mode;
    uint8 ADSDriving_mode;
    uint8 longitudCtrlSetSpeed;
    uint8 longitudCtrlSetDistance;
    uint8 LowBeamSt;
    uint8 HighBeamSt;
    uint8 HazardLampSt;
    uint8 LowHighBeamSt;
    uint8 HornSt;
    uint8 NNPSysState;
    uint8 acc_target_id;
    uint8 alc_warnning_target_id;
    uint8 alc_warnning_state;
};
struct AlgMcuEgoAVPMsg {
    uint8 AVPSysMode;
    uint8 system_command;
    uint8 avp_run_state;
    uint8 pnc_warninginfo;
};

struct AlgMcuEgoMemMsg {
    uint8 CDCS11_VoiceMode;
    uint8 RCTA_OnOffSet_mem;
    uint8 FCTA_OnOffSet_mem;
    uint8 DOW_OnOffSet_mem;
    uint8 RCW_OnOffSet_mem;
    uint8 LCA_OnOffSet_mem;
    uint8 TSR_OnOffSet_mem;
    uint8 TSR_OverspeedOnOffSet_mem;
    uint8 IHBC_OnOffSet_mem;
};

/* ******************************************************************************
    结构 名        :  AlgMcu2EgoFrame
    功能描述       :  MCU发往归控的算法交互信号
****************************************************************************** */
struct AlgMcu2EgoFrame : IDLBaseType {
    boolean isValid;
    AlgMcuEgoNNPMsg msg_mcu_nnp;
    AlgMcuEgoAVPMsg msg_mcu_avp;
    AlgMcuEgoMemMsg msg_mcu_mem;
    uint8 ta_pilot_mode;
    uint32 FCT2SOC_TBD_u32_01;
    uint32 FCT2SOC_TBD_u32_02;
    uint32 FCT2SOC_TBD_u32_03;
    uint32 FCT2SOC_TBD_u32_04;
    uint32 FCT2SOC_TBD_u32_05;
    uint8 drive_mode;
};
struct AlgAebToEgoFrame : IDLBaseType {
    uint8 AEB_state;
    uint8 AEB_target_id;
    uint8 FCW_state;
    uint8 FCW_target_id;
};
