#include "common.idl"
#include "type.idl"

struct MbdPosCalcDebug {
    double posecalc_posedata_timestamp;
    boolean posecalc_inputdata_valid;
    boolean posecalc_posedata_timecheck;
    boolean posecalc_enable;
    float posecalc_timedelay;
    double posedata_world_pos_x;
    double posedata_world_pos_y;
    float posecalc_vrf_vel_x;
    float posecalc_vrf_vel_y;
    float posecalc_vrf_acc_x;
    float posecalc_vrf_acc_y;
    float posedata_world_heading;
    float posedata_vrf_yawrate;
    double posecalc_world_pos_x;
    double posecalc_world_pos_y;
    float posedata_vrf_vel_x;
    float posedata_vrf_vel_y;
    float posedata_vrf_acc_x;
    float posedata_vrf_acc_y;
    float posecalc_world_vel_x;
    float posecalc_world_vel_y;
    float posecalc_world_acc_x;
    float posecalc_world_acc_y;
    float posecalc_world_heading;
    float posecalc_world_pitch;
};

struct MbdTrajCalcDebug {
    boolean trajCalc_trajdata_replaning_flag;
    uint32 trajcalc_trajdata_estop;
    uint32 trajcalc_trajdata_gearcmd;
    uint32 trajcalc_inputdata_valid;
    double trajcalc_trajdata_timestamp;
    double trajcalc_globaltime_timestamp;
    boolean trajcalc_trajdata_pointtime_check;
    boolean trajcalc_trajdata_timecheck;
    uint32 trajcalc_enable;
    uint32 trajcalc_lon_startpoint_index;
    float trajcalc_lon_linear_ratio;
    float trajcalc_lon_poserrcmd;
    float trajcalc_lon_headingcmd;
    float trajcalc_lon_velcmd;
    float trajcalc_lon_acc_cmd;
    float trajcalc_lon_curvcmd;
    uint32 trajcalc_lonpre_startpoint_index;
    float trajcalc_lonpre_linear_ratio;
    float trajcalc_lonpre_poserrcmd;
    float trajcalc_lonpre_headingcmd;
    float trajcalc_lonpre_velcmd;
    float trajcalc_lonpre_acc_cmd;
    float trajcalc_lonpre_curvrmd;
    double trajcalc_posedata_posex;
    double trajcalc_posedata_posey;
    uint32 trajcalc_lat_startpoint_index;
    float trajcalc_lat_linear_ratio;
    float trajcalc_lat_match_pointx;
    float trajcalc_lat_match_pointy;
    float trajcalc_lat_poserrcmd;
    float trajcalc_lat_headingcmd;
    float trajcalc_lat_velcmd;
    float trajcalc_lat_acc_cmd;
    float trajcalc_lat_curvcmd;
    double trajcalc_posedata_preposex;
    double trajcalc_posedata_preposey;
    uint32 trajcalc_latpre_startpoint_index;
    float trajcalc_latpre_linear_ratio;
    float trajcalc_latpre_match_pointx;
    float trajcalc_latpre_match_pointy;
    float trajcalc_latpre_poserrcmd;
    float trajcalc_latpre_headingcmd;
    float trajcalc_latpre_velcmd;
    float trajcalc_latpre_acc_cmd;
    float trajcalc_latpre_curvcmd;
};

struct MbdADASCalcDebug {
    uint8 adascalc_is_lccactive;
    float adascalc_trajparam_a0;
    float adascalc_trajparam_a1;
    float adascalc_trajparam_a2;
    float adascalc_trajparam_a3;
    uint8 adascalc_trp_replanlevel;
    uint8 adascalc_hostlindchgtoleft_bl;
    uint8 adascalc_hostlindchgtorght_bl;
    uint8 adascalc_accsystemstate;
    uint8 adascalc_accstopreq;
    float adascalc_deltavelocity;
    float adascalc_deltadist;
    float adascalc_drvrseltrgtspd_sg;
    uint8 adascalc_acc_smrsts;
    uint8 adascalc_enable;
    boolean adascalc_replanningflag;
    uint32 adascalc_gearcmd;
    uint8 adascalc_estop;
    float cal_adascalc_headdingoffset_rad;
    float adascalc_lat_poserrcmd;
    float adascalc_lat_headingcmd;
    float adascalc_lat_velcmd;
    float adascalc_latpre_curvcmd;
    float adascalc_lon_poserrcmd;
    float adascalc_lon_velcmd;
    float adascalc_a_acctrajcmd;
    uint8 adascalc_is_longtraj_replan;
    float adascalc_m_strajerror;
    float adascalc_trajparamlong_a0;
    float adascalc_trajparamlong_a1;
    float adascalc_trajparamlong_a2;
    float adascalc_trajparamlong_a3;
    float adascalc_trajparamlong_a4;
    float adascalc_trajparamlong_a5;
    float adascalc_v_spdtrajcmd;
};

struct MbdCtrlDecDebug {
    uint32 ctrldec_sysmode;
    boolean ctrldec_req_auto;
    boolean ctrldec_automode_is_estop;
    boolean ctrldec_is_gear_change_req;
    boolean ctrldec_is_stop_steer_ctrl;
    boolean ctrldec_is_vehicle_standstill;
    boolean ctrldec_is_steer_set_ok;
    uint32 ctrldec_trajcalc_geargmd;
    uint32 ctrldec_lat_sysmodecmd;
    uint32 ctrldec_lat_resetflag;
    float ctrldec_lat_sys_poserr;
    float ctrldec_lat_sys_yawff;
    float ctrldec_lat_sys_velff;
    float ctrldec_lat_sys_curvff;
    float ctrldec_lat_api_poscmd;
    float ctrldec_lat_api_yawcmd;
    float ctrldec_lat_api_curvcmd;
    float ctrldec_lat_api_steercmd;
    uint32 ctrldec_lon_sysmodecmd;
    uint32 ctrldec_lon_resetflag;
    float ctrldec_lon_sys_poserr;
    float ctrldec_lon_sys_velff;
    float ctrldec_lon_sys_accff;
    uint32 ctrldec_lon_sys_gearcmd;
    uint32 ctrldec_lon_sys_gear_ena;
    uint32 ctrldec_lon_sys_brk_emerg;
    float ctrldec_lon_api_poscmd;
    float ctrldec_lon_api_velff;
    float ctrldec_lon_api_acc_cmd;
    float ctrldec_lon_api_thrcmd;
    float ctrldec_lon_api_brkcmd;
    uint32 ctrldec_adascalc_geargmd;
    uint8 ctrldec_ctrl_err;
    uint8 ctrldec_actor_error;
    uint8 ctrldec_sensor_error;
    uint8 ctrldec_algorithm_error;
};

struct MbdLonCtrlDebug {
    uint8 lonctrl_modecmd;
    uint32 lonctrl_resetflag;
    float lonctrl_sys_poserr;
    float lonctrl_sys_velff;
    float lonctrl_sys_accff;
    uint32 lonctrl_sys_gearcmd;
    uint32 lonctrl_sys_gearena;
    uint32 lonctrl_sys_brkemerg;
    float lonctrl_api_poscmd;
    float lonctrl_api_velcmd;
    float lonctrl_api_acccmd;
    float lonctrl_api_thrcmd;
    float lonctrl_api_brkcmd;
    float lonctrl_fdbk_vx;
    float lonctrl_fdbk_ax;
    float lonctrl_fdbk_pitch;
    float lonctrl_fdbk_gear;
    float lonctrl_fdbk_reverse;
    float lonctrl_pos_dyn;
    float lonctrl_posctrl_p;
    float lonctrl_posctrl_i;
    float lonctrl_pos_poserr_filter;
    float lonctrl_pos_pi_velcmd;
    float lonctrl_pos_output_velcmd;
    float lonctrl_vel_dyn;
    float lonctrl_vel_velcmd_lmt;
    float lonctrl_vel_vel_err;
    float lonctrl_velctrl_p;
    float lonctrl_velctrl_i;
    float lonctrl_vel_pi_acc_cmd;
    float lonctrl_vel_pi_acccmd_filter;
    float lonctrl_vel_accpitch;
    float lonctrl_vel_accdamper;
    float lonctrl_vel_accff_filter;
    float lonctrl_vel_output_accCmd;
    float lonctrl_vel_output_accCmd_filter;
    float lonctrl_thrust_thr_dyn;
    float lonctrl_thrust_thr_accerr;
    float lonctrl_thrust_brk_dyn;
    float lonctrl_thrust_brk_accerr;
    float lonctrl_thrust_fdbk_ax_filter;
    float lonctrl_thrust_thr_acc_cmd_filter;
    float lonctrl_thrust_brk_acc_cmd_filter;
    float lonctrl_thrustctrl_thr_p;
    float lonctrl_thrustctrl_thr_i;
    float lonctrl_thrustctrl_brk_p;
    float lonctrl_thrustctrl_brk_i;
    float lonctrl_thrust_pi_thr_acc_cmd;
    float lonctrl_thrust_pi_brk_acc_cmd;
    float lonctrl_thrust_acc_cmd_filter_lmt;
    float lonctrl_thrust_acctothr_gain;
    float lonctrl_thrust_throut_throcmd;
    float lonctrl_thrust_acctobrk_gain;
    float lonctrl_thrust_brkout_brkcmd;
    float lonctrl_analog_autput_throtcmd;
    float lonctrl_analog_autput_brkcmd;
    float lonctrl_vel_mrac_cmd;
    float lonctrl_vel_reference_model;
    float lonctrl_accel_eso_cmd;
    float lonctrl_deccel_eso_cmd;
    float lonctrl_slope_estimate;
    float lonctrl_mass_estimate;
    uint8 lonctrl_error;
};

struct MbdLatCtrlDebug {
    uint8 latctrl_modecmd;
    uint32 latctrl_resetflag;
    float latctrl_sys_poserr;
    float latctrl_sys_yawff;
    float latctrl_sys_velff;
    float latctrl_sys_curvff;
    float latctrl_api_poscmd;
    float latctrl_api_yawcmd;
    float latctrl_api_curvcmd;
    float latctrl_api_steercmd;
    float latictrl_fdbk_vxb;
    float latictrl_fdbk_heading;
    float latictrl_fdbk_yawrate;
    float latictrl_fdbk_steer;
    uint8 latictrl_fdbk_gear;
    uint32 latictrl_fdbk_rvsflag;
    float latictrl_offset_dyn;
    float latictrl_offset_offseterr;
    float latictrl_offset_pi_torscmd;
    float latictrl_offset_torsrateffcmd;
    float latictrl_offset_output_yawcmd;
    float latictrl_offsetctrl_i;
    float latictrl_offsetctrl_p;
    float latictrl_tors_dyn;
    float latictrl_tors_pure_yawerr;
    float latictrl_tors_yawerr;
    float latictrl_yawctrl_p;
    float latictrl_yawctrl_i;
    float latictrl_tors_pi_torsrate;
    float latictrl_tors_pi_leadfilter_torsrate;
    float latictrl_tors_torsrateff;
    float latictrl_tors_output_yawratecmd;
    float latictrl_rate_dyn;
    float latictrl_rate_p;
    float latictrl_rate_i;
    float latictrl_rate_yawratecmd_lmt;
    float latictrl_rate_filter_yawratecmd_lmt;
    float latictrl_rate_pi_steer;
    float latictrl_rate_pi_filter_steer;
    float latictrl_rate_steerff;
    float latictrl_rate_output_front_steercmd;
    float latictrl_rate_output_front_steercmd_offset;
    float latictrl_rate_output_sw_steercmd;
    float latictrl_steer_steercmd_filter;
    float latictrl_steer_max_steerrate_value;
    float latictrl_steer_steercmd_lmt_filter;
    float latictrl_steer_output_steercmd;
    float latictrl_yaw_curve_compsate;
    float latictrl_rate_reference_model;
    float latictrl_rate_mrac_cmd;
    float latictrl_rate_eso_cmd;
    float latictrl_rate_steer_offset;
    float latictrl_rate_ramp_estimate;
    uint8 latictrl_error;
};

struct MbdCtrlOutputDebug {
    float ctrlout_brake_cmd;
    float ctrlout_throttle_cmd;
    float ctrlout_acc_cmd;
    uint8 ctrlout_gear_enable;
    uint8 ctrlout_gear_cmd;
    uint8 ctrlout_emerg_enable;
    float ctrlout_steer_cmd;
    float ctrlout_steer_torque_cmd;
};

struct MbdDebugData {
    MbdPosCalcDebug pos_calc_debug;
    MbdTrajCalcDebug traj_calc_debug;
    MbdADASCalcDebug adas_calc_debug;
    MbdCtrlDecDebug ctrl_dec_debug;
    MbdLonCtrlDebug lon_ctrl_debug;
    MbdLatCtrlDebug lat_ctrl_debug;
    MbdCtrlOutputDebug ctrl_output_debug;
    uint8 VersionNumber[20];
};

struct MbdData {
    MbdDebugData mbd_debug;
    boolean isValid;
};

struct Adas_MSG_0x8E {
    uint8 ADCS2_ADAS_EPSAngleReqSt;
    uint8 ADCS2_EPS_LDPState;
    uint8 ADCS2_NNP_SystemFaultStatus;
    uint8 ADCS_Pilot_SystemFaultStatus;
    uint8 ADCS2_ADAS_EPSLateralCtrlType;
    uint8 ADCS2_ADSDriving_mode;
    float ADCS2_ADAS_EPSAngleReq;
    uint8 ADCS2_ALCDirection;
    uint8 ADCS2_EPS_ELKState;
    uint8 ADCS2_longitudCtrlType;
    uint8 ADCS2_LongitudCtrlDecToStopReq;
    uint8 ADCS2_LongitudCtrlDriveOff;
    uint8 ADCS2_LongitudCtrlAccelCtrlReq;
    float ADCS2_LongitudCtrlTargetAccel;
};

struct Adas_MSG_0x8F {
    uint8 ADCS11_PA_GearReq;
    uint8 ADCS11_PA_GearPosReqVail;
    uint8 ADCS11_PA_prefillReq;
    uint8 ADCS11_PA_GearPosReq;
    uint8 ADCS11_PA_BrakemodeReq;
    uint8 ADCS11_PA_EpbReq;
    float ADCS11_PA_StopDistance;
    float ADCS11_PA_EPSAngleReq;
    uint8 ADCS11_PA_IDBControlReqV;
    float ADCS11_PA_TarDecel;
    uint8 ADCS11_PA_EPSAngleReqSt;
    uint8 ADCS11_PA_EPSAngleReqV;
    float ADCS11_PA_PAMaxSpd;
    uint8 ADCS11_PA_IDBControlReq;
    uint8 ADCS11_PA_TorqReq;
    uint8 ADCS11_PA_TorqReqValidity;
    uint8 ADCS11_PA_TarDecelreq;
    uint8 ADCS11_PA_ParkingFnMd;
    uint8 ADCS11_PA_StopReq;
    uint8 ADCS11_PA_StopDistanceValid;
    float ADCS11_PA_TorqReqValue;
    uint8 ADCS11_PA_IDB_TorqReqValidity;
    float ADCS11_PA_IDB_TorqReqValue;
};
struct Adas_MSG_0x136 {
    uint8 ADCS12_DCLCAudioplay;
    uint8 ADCS12_PilotAudioPlay;
    uint8 ADCS12_HandOffAudioplay;
    uint8 ADCS12_NNPCancelAudioPlay;
    uint8 ADCS12_MRMAudioPlay;
    uint8 ADCS12_NNP_ResumeAudioplay;
    uint8 ADCS12_Lcsndrequest;
    uint8 ADCS12_Lcsndrconfirm;
    uint8 ADCS12_DriveOffBroadcast;
    uint8 ADCS12_EyeOffBroadcast;
    uint8 ADCS12_longitudDisableInfo;
    uint8 ADCS12_SpeedAdaptComfirm;
    uint8 ADCS12_PayModeConfirm;
    uint8 ADCS12_longitudCtrlSysInfo;
    uint8 ADCS12_ADAS_DriveOffinhibition;
    uint8 ADCS12_P2N_State_Reminder;
    uint8 ADCS12_NNP_State_Reminder;
    uint8 ADCS12_NNP_LightRemind;
    uint8 ADCS12_LaneChangePendingAlert;
    uint8 ADCS12_NPilotSysInfo;
    uint8 ADCS12_LCAudioPlay;
    uint8 ADCS12_NNP_Scenarios_AudioPlay;
    uint8 ADCS12_NNP_RINO;
};

struct Adas_MSG_0x193 {
    uint8 ADCS8_LDWState;
    uint8 ADCS8_LDWWarnState;
    uint8 ADCS8_LDWMode;
    uint8 ADCS8_ELKMode;
    uint8 ADCS8_LDPELKWarnState;
    uint8 ADCS8_lateralCtrHandsEyesOffWarning;
    uint8 ADCS8_MissingExitAlert;
    uint8 ADCS8_LKSSetspeed;
    uint8 ADCS8_ACCState;
    uint8 ADCS8_lateralCtrtakeover;
    uint8 ADCS8_LateralCtrHandOffReleasewarning;
    uint8 ADCS8_LDPMode;
    uint8 ADCS8_LDPELKtakeoverWarningstate;
    uint8 ADCS8_longitudCtrlSetSpeed;
    uint8 ADCS8_NNP_Scenarios;
    uint8 ADCS8_longitudCtrlTakeOverReq;
    uint8 ADCS8_longitudCtrlSetDistance;
    uint8 ADCS8_longitudCtrlTargetValidity;
    uint8 ADCS8_ACCSystemFaultStatus;
    uint8 ADCS8_HornReq;
    uint8 ADCS8_DoorUnlock;
    uint8 ADCS8_ACCOnOffState;
    uint8 ADCS8_NNP_SOAAudioplay;
    uint8 ADCS8_TSR_SLFStatefeedback;
    uint8 ADCS8_VoiceNotifFrequency_mode;
    uint8 ADCS8_NPilot_SystemFaultStatus;
    uint8 ADCS8_NPilot_SysState;
    uint8 ADCS8_NNP_AutoOnOffSet;
    uint8 ADCS8_NNP_SystemFaultStatus;
    uint8 ADCS8_NNPSysState;
    uint8 ADCS8_Lanechangeinfor;
    uint8 ADCS8_DCLCSysState;
    uint8 ADCS8_LaneChangeSystemFaultStatus;
    uint8 ADCS8_LaneChangeWarning;
    uint8 ADCS8_ADAS_DriveOffPossilbe;
    uint8 ADCS8_DriveOffinhibitionObjType;
    uint8 ADCS8_VoiceMode;
    uint8 ADCS8_ALC_mode;
    uint8 ADCS8_NNP_State;
    uint8 ADCS8_Lanechangedirection;
    uint8 ADCS8_ADSDriving_mode;
    uint8 ADCS8_NNP_MRM_status;
};

struct FctEEPromInfo {
    uint8 MCU_stat_LDWMode_u8;
    uint8 MCU_V_LKSSetspeed_u8;
    uint8 MCU_stat_LDPMode_u8;
    uint8 MCU_stat_VoiceMode_u8;
    uint8 MCU_stat_ACCOnOffState_u8;
    uint8 MCU_stat_DCLCSysState_u8;
    uint8 MCU_stat_NNPState_u8;
    uint8 MCU_stat_AutoOnOffSet_u8;
    uint8 MCU_stat_ALCMode_u8;
    uint8 MCU_stat_ADSDrivingMode_u8;
    uint8 MCU_stat_SLFStatefeedback_u8;
};

struct Adptr_Out {
    Adas_MSG_0x8E Adptr_Out_Msg_0x8E;
    Adas_MSG_0x8F Adptr_Out_Msg_0x8F;
    Adas_MSG_0x136 Adptr_Out_Msg_0x136;
    Adas_MSG_0x193 Adptr_Out_Msg_0x193;
};

struct CtrlEEPromInfo {
    float CtrlYawrateOffset;
    float CtrlYawOffset;
    float CtrlAxOffset;
    float CtrlSteerOffset;
    float CtrlAccelDeadzone;
};

struct HafChassis {
    uint8 YawrateFdbkValid;
    uint8 AxFdbkValid;
    uint8 HsaActive;
    uint8 HsaFail;
    uint8 VehicleStandstill;
    uint8 AccEnable;
    float AccCmdFdbk;
    uint8 VehicleSpdValid;
    uint8 PaPrefillFlag;
    uint8 FLWhlVelocityValid;
    float FLWhlVelocity;
    uint8 FRWhlVelocityValid;
    float FRWhlVelocity;
    uint8 RRWhlDir;
    uint8 RLWhlDir;
    uint8 FRWhlDir;
    uint8 FLWhlDir;
    uint8 RLWhlVelocityValid;
    float RLWhlVelocity;
    uint8 RRWhlVelocityValid;
    float RRWhlVelocity;
    uint8 SteerFdbkValid;
    uint8 SteerFdbkSpdValid;
    uint8 SteerCalibrated;
    uint8 WarningRed;
    uint8 WarningYellow;
    float SteerFdbkSpd;
    uint8 AyFdbkValid;
    float AyFdbk;
    float VxFdbk;
    float VehicleSpdDisplay;
    float AxFdbk;
    float PitchFdbk;
    float YawFdbk;
    float YawRateFdbk;
    float SteerFdbk;
    uint8 GearFdbk;
    float VehicleGyroX;
    float VehicleGyroY;
    float VehicleGyroZ;
    float VehicleAccelX;
    float VehicleAccelY;
    float VehicleAccelZ;
    uint8 IDB6_EPBStatus;
    uint8 IDB1_BrakePedalApplied;
    uint8 IDB9_PA_ApaCtrlSts;
    uint8 EPS2_ADAS_Active;
    uint8 EPS2_PA_Active;
    uint8 VCU14_PAActiv;
};

struct HafGlobalTime {
    uint32 TimeStampSec;
    uint32 TimeStampNsec;
    uint8 GetTimeEnable;
};
struct Inputs_MCU {
    uint8 MCU_stat_LDWMode_u8;
    uint8 MCU_V_LKSSetspeed_u8;
    uint8 MCU_stat_LDPMode_u8;
    uint8 MCU_stat_VoiceMode_u8;
    uint8 MCU_stat_ACCOnOffState_u8;
    uint8 MCU_stat_DCLCSysState_u8;
    uint8 MCU_stat_NNPState_u8;
    uint8 MCU_stat_AutoOnOffSet_u8;
    uint8 MCU_stat_ALCMode_u8;
    uint8 MCU_stat_ADSDrivingMode_u8;
    uint8 MCU_stat_SLFStatefeedback_u8;
    uint32 MCU_indx_FuncConfDID_u32;
};

struct HafCan3Bus_Rx {
    uint8 ACU1_Driver_Buckle;
    boolean ACU2_LatAccSensorValueV;
    float ACU2_LatAccSensorValue;
    boolean ACU2_VehicleDynYawRateV;
    boolean ACU2_LongAccSensorValueV;
    float ACU2_LongAccSensorValue;
    float ACU2_VehicleDynYawRat;
    uint8 BDCS1_PowerMode;
    boolean BDCS1_LeftTurnLightSt;
    boolean BDCS1_RightTurnLightSt;
    boolean BDCS1_HazardLampSt;
    boolean BDCS1_TrunkLockSts;
    boolean BDCS1_HoodAjarSts;
    uint8 BDCS6_FrontWiperSts;
    uint8 CDCS11_FCW_OnOffSet;
    uint8 CDCS11_AEB_OnOffSet;
    uint8 CDCS11_FCW_WarnTiming;
    uint8 CDCS5_FactoryReset;
    uint8 CDCS5_ResetAllSetup;
    uint8 DDCU1_FLDoorAjar;
    uint8 DDCU1_RLDoorAjar;
    boolean EPS1_SteeringAngleValid;
    boolean EPS1_SteerAngleSpdValid;
    boolean EPS1_HSTWCalibrated;
    float EPS1_SteeringAngle;
    float EPS1_SteerAngleSpd;
    boolean EPS2_ADAS_Available;
    boolean EPS1_WarningLampRed;
    boolean EPS1_WarningLampYellow;
    float ICU2_Odometer;
    boolean IDB1_BrakePedalApplied;
    boolean IDB1_BrakePedalAppliedV;
    uint8 IDB1_FailedState;
    float IDB2_FLWhlPulCnt;
    float IDB2_FRWhlPulCnt;
    float IDB3_MasterCylPressure;
    boolean IDB3_MasterCylPressureInvalid;
    boolean IDB3_VehicleSpdValid;
    float IDB3_VehicleSpd;
    boolean IDB4_FLWhlVelocityValid;
    float IDB4_FLWhlVelocity;
    boolean IDB4_FRWhlVelocityValid;
    float IDB4_FRWhlVelocity;
    uint8 IDB4_RRWhlDir;
    uint8 IDB4_RLWhlDir;
    uint8 IDB4_FRWhlDir;
    uint8 IDB4_FLWhlDir;
    boolean IDB4_RRWhlVelocityValid;
    boolean IDB4_RLWhlVelocityValid;
    float IDB4_RLWhlVelocity;
    float IDB4_RRWhlVelocity;
    float IDB4_RLWhlPulCnt;
    float IDB4_RRWhlPulCnt;
    boolean IDB4_RLWhlPulCntValid;
    boolean IDB4_RRWhlPulCntValid;
    boolean IDB5_BrakeDiscTempSts;
    uint8 IDB5_VehicleStanstill;
    boolean IDB5_JerkActive;
    boolean IDB5_Jerkfail;
    uint8 IDB5_ADAS_PrefillSts;
    boolean IDB5_DBSavailable;
    boolean IDB5_Prefillavailable;
    boolean IDB5_ABAactive;
    boolean IDB5_AEBactive;
    uint8 IDB5_AEB_Enable;
    uint8 IDB6_EPBStatus;
    uint8 IDB6_EPBAvailable;
    boolean IDB7_ESCFail;
    boolean IDB7_ESCActive;
    boolean IDB7_ABSActive;
    boolean IDB7_EBD_Fail;
    boolean IDB7_HBAActive;
    boolean IDB7_HBAFail;
    boolean IDB7_TCSActive;
    boolean IDB7_TCSDisable;
    boolean IDB7_TCSFail;
    boolean IDB7_ARPACTIVE;
    boolean IDB7_ARPFailure;
    boolean IDB7_ABSFail;
    boolean ICU1_VehicleSpdDisplayValid;
    float ICU1_VehicleSpdDisplay;
    uint8 VCU5_ActGear;
    boolean VCU5_ActGearValid;
    uint8 VCU5_PwrTrainFailureLevel;
    uint8 VCU5_READYLightSts;
    boolean VCU5_AccelPositionValid;
    uint8 VCU5_AccelPosition;
    uint8 PDCU1_FRDoorAjar;
    uint8 PDCU1_RRDoorAjar;
    uint16 CalendarYear;
    uint8 CalendarMonth;
    uint8 CalendarDay;
    uint8 HourOfDay;
    uint8 MinuteOfHour;
    uint8 SecsOfMinute;
    boolean TimeDspFmt;
};

struct HafSwc2AEBType {
    boolean VoiceMode;
    uint8 FCW_WarnTiming_Restore;
};

struct HafLidarPercpAlgoFailed {
    uint8 algo_configload_error;
    uint8 algo_pointcloud_preproc_error;
    uint8 algo_target_detn_error;
    uint8 algo_target_track_error;
    uint8 alog_grd_detn_error;
    uint8 algo_lane_detn_error;
    uint8 algo_freespace_detn_error;
};
struct HafLidarPercpDataFailed {
    uint8 data_l_comloss_error;
    uint8 data_l_vldt_error;
    uint8 data_r_comloss_error;
    uint8 data_r_vldt_error;
};
struct HafLidarPercpAlgoIntrFailed {
    uint8 algo_intr_configload_error;
    uint8 algo_intr_module_error;
};
struct HafLidarPercpCalibFailed {
    uint8 Calib_l_lidar_error;
    uint8 Calib_r_lidar_error;
};

struct HafLidarFailed {
    uint8 Ins_data_Failed;
    HafLidarPercpAlgoFailed Lidar_Percp_Algo_Failed;
    HafLidarPercpDataFailed Lidar_Percp_Data_Failed;
    HafLidarPercpAlgoIntrFailed Lidar_Percp_Algo_Intr_Failed;
    HafLidarPercpCalibFailed Lidar_Percp_Calib_Failed;
};

struct HafAebFcwFaultBusType {
    uint8 FID_AEBSYS_Failed;
    uint8 FID_AEB_Failed;
    HafLidarFailed Lidar_Failed;
};

struct HafCan3Bus_Tx {
    boolean ADCS2_AEBVehicleHoldReq;
    boolean ADCS2_AEBFullBrake;
    boolean ADCS2_AEBPartialBrake;
    uint8 ADCS2_AEB_DBSLevel;
    boolean ADCS2_AEBPrefillReq;
    boolean ADCS2_AEB_JerkReq;
    float ADCS2_AEBTargetDeceleration;
    uint8 ADCS2_AEB_JerkLevel;
    uint8 ADCS8_AEB_SystemFaultStatus;
    boolean ADCS8_AEB_SystemStatus;
    uint8 ADCS8_FCWSystemFaultStatus;
    uint8 ADCS8_FCWStatus;
    uint8 ADCS8_FCWSensitiveLevel;
    boolean ADCS8_FCW_State;
    uint8 ADCS8_SystemFault;
    boolean ADCS12_FCWWarnAudioplay;
};

struct HafAEB2SwcType {
    uint8 ADCS_AEB_Triggering_object_ID;
    uint8 ADCS_FCW_Triggering_object_ID;
    uint8 ADCS2_AEB_JerkLevel;
    uint8 ADCS8_FCWStatus;
    boolean Fusa_MonitorFault;
};

struct HafAEB2NVMType {
    uint8 ADCS8_FCWSensitiveLevel;
    uint32 ADCS_AEB_Version;
};

struct HafAEBSDebugBusType {
    boolean CIB_GasPedal_OR;
    boolean CIB_HighBrakeTimer_On;
    boolean CIB_OverrideTimer_On;
    boolean CIB_Steering_OR;
    boolean CIB_Inhibit_Steering_OR;
    boolean CIB_StationaryObjectDelay_On;
    boolean CIB_Brake_Release;
    boolean CIB_FCW;
    float CIB_Filt_Accel_mpss;
    uint8 CIB_Steer_Rate_Flag;
    float CIB_Time_To_Brake;
    float CIB_Time_To_Turn;
    boolean CIB_PCSAlgoEntered;
    uint8 CIB_Activation_Target_ID;
    boolean CIB_NewTrackData;
    boolean CIB_ProcessEachTrack;
    boolean CIB_ProcessCmbbTrack;
    boolean CIB_PCSEntryGatePassed;
    boolean CIB_InPathGatePassed;
    boolean CIB_HighBrakeDeploy;
    boolean CIB_LowBrakeDeploy;
    uint8 CIB_Brake_Level;
    boolean IMUSecondaryPlausibilityFault;
    boolean IMUPrimaryPlausibilityFault;
    boolean WSSPlausibilityFault;
    boolean SASPlausibilityFault;
    float CIB_indicator;
    uint8 CIB_Steer_Rate_Flag1;
    float CIB_Time_To_Brake1;
    float CIB_Time_To_Turn1;
    uint32 CIB_Inhibit_1_Flags;
    uint32 CIB_Inhibit_0_Flags;
    uint32 CIB_Inhibit_3_Flags;
    uint32 CIB_Inhibit_2_Flags;
    uint32 CIB_Inhibit_5_Flags;
    uint32 CIB_Inhibit_4_Flags;
    float CIBMovObjRange;
    float CIBMovObjRangeAccel;
    float CIBMovObjRangeRate;
    uint8 CIBMovObjTrackID;
    float CIBMovObjAngle;
    boolean LowSpeed_ClutterON;
    boolean InTunnelFlag_bool;
    uint32 CIBMovObjTrackPower;
    float CIBMovOffsetTrackRange;
    float CIBStaObjRange;
    float CIBStaObjRangeAccel;
    float CIBStaObjRangeRate;
    uint8 CIBStaObjTrackID;
    float CIBStaObjAngle;
    uint32 CIBStaObjTrackPower;
    float CIBStaOffsetTrackRange;
    uint16 FCW_Ref_indicator;
    uint32 FCW_Inhibit_1_Flags;
    uint32 FCW_Inhibit_0_Flags;
    uint32 FCW_Inhibit_3_Flags;
    uint32 FCW_Inhibit_2_Flags;
    uint32 FCW_Inhibit_5_Flags;
    uint32 FCW_Inhibit_4_Flags;
    uint8 FCWMovObjTrackID;
    uint8 FCWMovComponent;
    float FCWMovWarnRange;
    float FCWCIPVRange;
    float FCWCIPVRangeRate;
    float FCWLeadSpeed_mps;
    float FCWLeadAccel_mpss;
    uint8 FCA_Target_ID;
    boolean Allow_FCA;
    uint32 FCWMovPower;
    boolean FCWChimeSuppress;
    boolean FCA_State;
    float FCWCaution;
    float FCWHostAccel;
    float FCWReactionTime;
    boolean FCWAllowFCWCaution;
    float FCWStatAngle;
    uint8 FCA_Warning_State;
    float FCWMovAngle;
    uint8 FCWStatObjTrackID;
    uint8 FCWStatComponent;
    float FCWCIPSRange;
    float FCWStatWarnRange;
    uint8 FCWCIPSLatTimer;
    float FCWCIPSRangeRate;
    uint32 CIB_TSL_1_Flags;
    uint32 CIB_TSL_0_Flags;
    uint32 FCW_TSL_1_Flags;
    uint32 FCW_TSL_0_Flags;
};
struct AEBFCW_DataRecordFrame {
    HafCan3Bus_Rx Pi_AEBCan3BusRx;
    HafSwc2AEBType HafSwc2AEBTypeData;
    HafAebFcwFaultBusType HafAebFcwFaultBus;
    HafCan3Bus_Tx Pi_AEBCan3BusTx;
    HafAEB2SwcType HafAEB2SwcTypeData;
    HafAEB2NVMType HafAEB2NVMTypeData;
    HafAEBSDebugBusType HafAEBSDebugBusTypeData;
};

struct AebRecordData {
    AEBFCW_DataRecordFrame aebfcw_datarecord;
    boolean isValid;
};

struct VEH_CAN_Inputs_EP40 {
    uint8 IDB1_BrakePedalApplied;
    uint8 IDB1_BrakePedalAppliedV;
    uint8 CS1_GearPositionReqSt;
    uint8 CS1_TurnLightReqSt;
    uint8 CS1_GearPositionReqStValid;
    uint8 SWSM_A_CruiseDistance_Add;
    uint8 SWSM_A_CruiseDistance_Minus;
    uint8 Region_A_SwError;
    uint8 SWSM_A_CruiseSpeed_Add;
    uint8 SWSM_A_CruiseSpeed_Minus;
    uint8 SWSM_A_CD_Add_Overtime;
    uint8 SWSM_A_CD_Minus_Overtime;
    uint8 IDB6_EPBAvailable;
    uint8 IDB6_EPBStatus;
    uint8 ACU1_CrashStatus;
    float ACU2_LatAccSensorValue;
    uint8 ACU2_LatAccSensorValueV;
    float ACU2_LongAccSensorValue;
    uint8 ACU2_LongAccSensorValueV;
    float ACU2_VehicleDynYawRate;
    uint8 ACU2_VehicleDynYawRateV;
    float IDB3_VehicleSpd;
    uint8 IDB3_VehicleSpdValid;
    float IDB3_MasterCylPressure;
    uint8 IDB3_MasterCylPressureInvalid;
    float VCU5_AccelPosition;
    uint8 VCU5_ActGear;
    uint8 VCU5_ActGearValid;
    uint8 VCU5_AccelPositionValid;
    uint8 VCU5_READYLightSts;
    uint8 VCU5_DriverOvertakeMode;
    uint8 VCU5_EmuEngineSts;
    float EPS1_SteeringAngle;
    float EPS1_SteerAngleSpd;
    uint8 EPS1_SteerAngleSpdValid;
    uint8 EPS1_SteeringAngleValid;
    float EPS1_TorsionBarTorque;
    uint8 EPS1_TorsionBarTorqueValid;
    uint8 EPS2_ADAS_Available;
    float EPS2_MotCntrl;
    uint8 EPS2_PA_Available;
    uint8 EPS2_PA_Active;
    uint8 EPS2_MotCntrlValid;
    uint8 EPS2_PA_CtrlAbortFeedback;
    uint8 BDCS3_BackDoorAjar;
    uint8 BDCS1_FrontLampSt;
    uint8 BDCS1_HazardLampSt;
    uint8 BDCS1_HazardSwSt;
    uint8 BDCS1_HighBeamSW;
    uint8 BDCS1_HighBeamSt;
    uint8 BDCS1_LeftTurnLightSt;
    uint8 BDCS1_LowBeamSt;
    uint8 BDCS1_RightTurnLightSt;
    uint8 BDCS1_TurnLightSW;
    uint8 BDCS1_PowerMode;
    uint8 BDCS1_TrunkLockSts;
    uint8 BDCS1_HoodAjarSts;
    uint8 BDCS4_FLTyre_PressureWarn;
    uint8 BDCS4_FRTyre_PressureWarn;
    uint8 BDCS4_RLTyre_PressureWarn;
    uint8 BDCS4_RRTyre_PressureWarn;
    uint8 BDCS6_FrontWiperParkPos;
    uint8 BDCS6_FrontWiperSts;
    uint8 ACU1_Driver_Buckle;
    uint8 IDB7_ABSActive;
    uint8 IDB7_ESCActive;
    uint8 IDB7_TCSActive;
    uint8 IDB7_TCSFail;
    uint8 IDB7_ABSFail;
    uint8 IDB7_ESCFail;
    uint8 IDB7_HDCEnabled;
    uint8 IDB7_ESCDisable;
    uint8 IDB7_HDCAtive;
    uint8 IDB7_DynParkBrkByIDBActive;
    uint8 IDB7_TCSDisable;
    uint8 IDB7_ARPACTIVE;
    uint8 IDB7_EBD_Fail;
    uint8 IDB7_ARPFailure;
    uint8 IDB4_FLWhlDir;
    float IDB4_FLWhlVelocity;
    uint8 IDB4_FLWhlVelocityValid;
    uint8 IDB4_FRWhlDir;
    float IDB4_FRWhlVelocity;
    uint8 IDB4_FRWhlVelocityValid;
    uint8 IDB4_RLWhlDir;
    float IDB4_RLWhlVelocity;
    uint8 IDB4_RLWhlVelocityValid;
    uint8 IDB4_RRWhlDir;
    float IDB4_RRWhlVelocity;
    uint8 IDB4_RRWhlVelocityValid;
    uint8 CDCS3_DriveModeSet;
    uint8 CDCS15_NNP_DriverStatus;
    uint8 CDCS13_SwSmMode;
    uint8 DDCU1_FLDoorAjar;
    uint8 DDCU1_RLDoorAjar;
    uint8 DDCU1_MirrorFoldSt;
    uint8 ICU1_VehicleSpdDisplayValid;
    float ICU1_VehicleSpdDisplay;
    uint8 IDB5_BrakeDiscTempSts;
    uint8 IDB5_VehicleStanstill;
    uint8 IDB5_ACC_ReqLim;
    uint8 IDB5_ABAactive;
    uint8 IDB5_ACC_Enable;
    float IDB5_ACC_ReferenceAccel;
    uint8 IDB5_DriverOverride;
    uint8 IDB9_PA_CtrlAbortFeedback;
    uint8 IDB9_PA_ParkingBrkMdSeln;
    uint8 IDB9_PA_ParkingFnMd;
    uint8 IDB9_PA_ParkingAvailable;
    uint8 IDB9_PA_ApaCtrlSts;
    uint8 IDB9_PAStandStill;
    uint8 IDB9_PASts;
    float MCU1_MotorSpeed;
    float MCU1_ControllerTorque;
    float MCU1_CurrentTorque;
    uint8 MCU1_CurrentTorqueValid;
    uint8 PDCU1_FRDoorAjar;
    uint8 PDCU1_RRDoorAjar;
    uint8 VCU14_PAAvailable;
    uint8 VCU14_ACC_Ready;
    uint8 VCU14_PAActive;
    uint8 VCU14_PA_ParkingFnMd;
    uint8 VCU14_PA_FailCode;
    uint8 VCU14_Gear_PAActive;
    uint8 VCU14_Gear_PAAvailable;
    uint8 VCU14_Gear_ErrorSts_M01;
    uint8 VCU4_PA_DeceltorSts;
    uint8 VCU4_PA_TargetTrqValueValidity;
    uint8 VCU14_Gear_PACtrlAbortFeedback;
    float VCU4_PA_TargetTrqValue;
    float VCU7_MaxMotPosTq;
    float VCU7_MaxMotGenTq;
    float VCU7_MaxFMotPosTq;
    float VCU7_MaxFMotGenTq;
    uint8 CDCS11_LKSSetspeed;
    uint8 CDCS11_LDW_OnOffSet;
    uint8 CDCS11_LCA_OnOffSet;
    uint8 CDCS11_TSR_OnOffSet;
    uint8 CDCS11_NNP_OnOffSet;
    uint8 CDCS11_DCLCSysState;
    uint8 CDCS11_ALCSysState;
    uint8 CDCS11_DriveOffPossilbeswitch;
    uint8 CDCS11_DriveOffinhibitionswitch;
    uint8 CDCS11_ADAS_SndCtrlOnOff;
    uint8 CDCS11_VoiceMode;
    uint8 CDCS11_NNP_Active_OnOffSet;
    uint8 CDCS11_ALC_mode;
    uint8 CDCS11_ADSDriving_mode;
    uint8 CDCS11_TSR_OverspeedOnoffSet;
    uint8 CDCS11_NNP_AutoOnOffSet;
    uint8 CDCS11_SnCtrl_NNP_OnOff;
    uint8 CDCS11_TSR_SLFOnOffSet;
    uint8 CDCS11_APA_FunctionMode;
    uint8 CDCS11_TrackreverseSW;
    uint8 CDCS11_SetPathwaySW;
    uint8 CDCS11_PA_changeLanguage;
    uint8 CDCS11_LDP_OnOffSet;
    uint8 CDCS11_RPASw;
    uint8 CDCS11_SetSw;
    uint8 CDCS11_SoundCtrlSetReq;
    uint8 CDCS11_location_sw;
    uint8 CDCS11_Pathrefresh;
    uint8 CDCS11_HPAGuideSW;
    uint8 CDCS11_HPAPathwaytoCloudSW;
    uint8 CDCS11_PathlearningSw;
    uint8 CDCS11_PA_screenMd;
    uint8 CDCS11_PASw;
    uint8 CDCS11_PA_Recover;
    uint8 CDCS_Lcsndrequest;
    uint8 CDCS_Lcsndconfirm;
    uint8 CDCS_SpdAdaptComfirm;
    uint8 CDCS_PayModeConfirm;
    uint8 CDCS11_SelectSlotID;
    uint8 CDCS11_ParkingInReq;
    uint8 CDCS11_ParkingOutReq;
    uint8 CDCS11_RPA_FunctionMode;
    uint8 CDCS11_MOD_Sound_Sw;
    uint8 CDCS11_MOD_BSD_Sw;
    uint8 CDCS11_PA_FRS_OnOffSet;
    uint8 CDCS11_PA_3D_OnOffSet;
    uint8 CDCS11_PA_measure_OnOffSet;
    uint8 CDCS11_MODSw;
    uint8 CDCS11_VoiceNotifFrequency_mode;
    uint8 CDCS11_ACCOnOffSet;
    uint8 CDCS11_HPASw;
    uint8 CDCS11_DeleteMapID;
    uint8 CDCS11_UploadMapID;
    uint8 CDCS11_HPAActiveConfirm;
    uint8 CDCS11_HPApreparkingSw;
    uint8 CDCS11_HPAPathwaytoCloud_WorkSts;
    uint8 CDCS11_ParkingoutSlot_Type;
    uint8 CDCS11_ParkingoutSlot_Dire;
    uint8 CDCS11_OptionalSlot_Type;
    uint8 CDCS11_OptionalSlot_Dire;
    float CDCS11_OptionalSlotAngle;
    uint8 CDCS11_ELK_OnOffSet;
    uint8 ADCS2_AEBPartialBrake;
    uint8 ADCS2_AEBFullBrake;
    uint8 ADCS2_AEBPrefillReq;
    uint8 ADCS2_AEB_JerkReq;
    uint8 CDCS5_ResetAllSetup;
    uint8 CDCS5_FactoryReset;
    uint8 ADCS8_FRS_Fail;
    uint8 ADCS8_FVC_120_Fail;
    uint8 ADCS8_FVC_30_Fail;
    uint8 ADCS8_TSR_SpeedSign;
    uint8 ADCS8_TSRState;
    uint8 ADCS8_LCALeftWarnSt;
    uint8 ADCS8_LCARightWarnSt;
    uint8 ADCS11_PA_IDBControlReq;
    uint8 ADCS11_Parking_WorkSts;
    uint8 BTM2_ConnectSts;
    uint8 EPS1_HSTWCalibrated;
    uint8 VCU5_DriveMode_fb;
};

struct ADAS_DataRecordFrame {
    FctEEPromInfo pFCT_FctEEPromInfo;
    Adptr_Out pAdptrOut_Adptr_Out;
    CtrlEEPromInfo pCtrl_CtrlEEPromInfo;
    HafChassis rAdptrOut_HafChassisInfo;
    HafGlobalTime rCtrl_GlobalTime;
    Inputs_MCU rAdptrIn_MCU;
    VEH_CAN_Inputs_EP40 rAdptrIn_VEH_CAN;
};

struct AdasRecordData : IDLBaseType {
    ADAS_DataRecordFrame adas_datarecord;
    boolean isValid;
};

struct AlgMcuDebugFrame : IDLBaseType {
    MbdDebugData DebugData;
};
