%YAML:1.0

log:
   level: 1
   mode: 1
   file: ./

interfaces:
    - name: can7
      type: CANFD_16_BYTE # CANFD_16_BYTE/CANFD_8_BYTE/CAN_STANDARD
      can_id: 255 # decimical
      crc_enable: true
      interval_ms: 1000
      timeout_ms: 100
      data_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # 16 bytes

    - name: can8
      type: CANFD_16_BYTE # CANFD_16_BYTE/CANFD_8_BYTE/CAN_STANDARD
      can_id: 255 # decimical
      crc_enable: true
      interval_ms: 1000
      timeout_ms: 100
      data_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # 16 bytes
