/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2023. All rights reserved.
 */

#ifndef HOZONEXECUTABLE_COMMONRECVBASE_EXECUTABLE_H
#define HOZONEXECUTABLE_COMMONRECVBASE_EXECUTABLE_H

#include "ara/adas/adasserviceinterface_proxy.h"
#include "hozon/hmi2router/hozoninterface_hmi2router_proxy.h"
#include "hozon/hmi_planningdec/hozoninterface_planningdecisioninfo_proxy.h"
#include "hozon/interface/aeb2ego/hozoninterface_aeb2ego_proxy.h"
#include "hozon/interface/canfdmsg/hozoninterface_canfdmsg_proxy.h"
#include "hozon/interface/chassis/hozoninterface_chassis_proxy.h"
#include "hozon/interface/control/hozoninterface_control_proxy.h"
#include "hozon/interface/debugcontrol/hozoninterface_debugcontrol_proxy.h"
#include "hozon/interface/debugpb/hozoninterface_debugpb_proxy.h"
#include "hozon/interface/debugplan/hozoninterface_debugplan_proxy.h"
#include "hozon/interface/ego2mcu/hozoninterface_ego2mcu_proxy.h"
#include "hozon/interface/egohmi/hozoninterface_egohmi_proxy.h"
#include "hozon/interface/freespace/hozoninterface_freespace_proxy.h"
#include "hozon/interface/gnssinfo/hozoninterface_gnssinfo_proxy.h"
#include "hozon/interface/imu/hozoninterface_imuinfo_proxy.h"
#include "hozon/interface/ins/hozoninterface_insinfo_proxy.h"
#include "hozon/interface/laneline/hozoninterface_laneline_proxy.h"
#include "hozon/interface/latency_test_1k/hozoninterface_latencytest1k_proxy.h"
#include "hozon/interface/latency_test_2k/hozoninterface_latencytest2k_proxy.h"
#include "hozon/interface/latency_test_500b/hozoninterface_latencytest500b_proxy.h"
#include "hozon/interface/latency_test_5k/hozoninterface_latencytest5k_proxy.h"
#include "hozon/interface/loc_element/hozoninterface_loc_element_proxy.h"
#include "hozon/interface/location/hozoninterface_location_proxy.h"
#include "hozon/interface/location/hozoninterface_locationhdmapinfo_proxy.h"
#include "hozon/interface/location/hozoninterface_locationmonitor_proxy.h"
#include "hozon/interface/location/hozoninterface_locationnodeinfo_proxy.h"
#include "hozon/interface/lowspeedbsd/hozoninterface_low_spd_bsd_proxy.h"
#include "hozon/interface/mapmsg/hozoninterface_mapmsg_proxy.h"
#include "hozon/interface/mcu2ego/hozoninterface_mcu2ego_proxy.h"
#include "hozon/interface/objcamera/hozoninterface_obj_camera_proxy.h"
#include "hozon/interface/objfusion/hozoninterface_obj_fusion_proxy.h"
#include "hozon/interface/objlidar/hozoninterface_obj_lidar_proxy.h"
#include "hozon/interface/objradar/hozoninterface_obj_radar_proxy.h"
#include "hozon/interface/objsignal/hozoninterface_obj_signal_proxy.h"
#include "hozon/interface/ocr/hozoninterface_ocr_proxy.h"
#include "hozon/interface/parkinglot/hozoninterface_parkinglot_proxy.h"
#include "hozon/interface/perceptioninfo/hozoninterface_perceptioninfo_proxy.h"
#include "hozon/interface/planning/hozoninterface_planning_proxy.h"
#include "hozon/interface/pointcloud/hozoninterface_pointcloud_proxy.h"
#include "hozon/interface/prediction/hozoninterface_prediction_proxy.h"
#include "hozon/interface/proto/hozoninterface_proto_proxy.h"
#include "hozon/interface/state_machine/hozoninterface_fieldtest_proxy.h"
#include "hozon/interface/state_machine/hozoninterface_statemachine_proxy.h"
#include "hozon/interface/uss/hozoninterface_uss_proxy.h"
#include "hozon/interface/ussinfo/hozoninterface_ussinfo_proxy.h"
#include "hozon/interface/vehicle_data_collect/hozoninterface_vehicle_data_collect_proxy.h"
#include "mdc/cam/camera/cameradecodedmbufserviceinterface_proxy.h"
#include "mdc/disp/display/displayimagembufserviceinterface_proxy.h"

#endif // HOZONEXECUTABLE_COMMONRECVBASE_EXECUTABLE_H
