#ifndef HW_NVMEDIA_COMPILE_H
#define HW_NVMEDIA_COMPILE_H

#include "hw_video_modules_common.h"

#define HW_NVMEDIA_PROJ_IMX728 0
#define HW_NVMEDIA_PROJ_ISX021 1
#define HW_NVMEDIA_PROJ_GROUPA 2
#define HW_NVMEDIA_PROJ_GROUPB 3
#define HW_NVMEDIA_PROJ_GROUPC 4
#define HW_NVMEDIA_PROJ_MULTIGROUP 5
#define HW_NVMEDIA_PROJ_IPC_PRODUCER 6
#define HW_NVMEDIA_PROJ_IPC_CONSUMER_CUDA 7
#define HW_NVMEDIA_PROJ_IPC_CONSUMER_ENC 8
#define HW_NVMEDIA_PROJ_MULTIIPC_PRODUCER 9
#define HW_NVMEDIA_PROJ_MULTIIPC_CONSUMER_CUDA 10
#define HW_NVMEDIA_PROJ_MULTIIPC_CONSUMER_ENC 11

#ifdef __HW_NVMEDIA_PROJ_USING_IMX728
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_IMX728
#elif __HW_NVMEDIA_PROJ_USING_ISX021
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_ISX021
#elif __HW_NVMEDIA_PROJ_USING_GROUPA
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_GROUPA
#elif __HW_NVMEDIA_PROJ_USING_GROUPB
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_GROUPB
#elif __HW_NVMEDIA_PROJ_USING_GROUPC
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_GROUPC
#elif __HW_NVMEDIA_PROJ_USING_MULTIGROUP
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_MULTIGROUP
#elif __HW_NVMEDIA_PROJ_IPC_PRODUCER
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_IPC_PRODUCER
#elif __HW_NVMEDIA_PROJ_IPC_CONSUMER_CUDA
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_IPC_CONSUMER_CUDA
#elif __HW_NVMEDIA_PROJ_IPC_CONSUMER_ENC
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_IPC_CONSUMER_ENC
#elif __HW_NVMEDIA_PROJ_MULTIIPC_PRODUCER
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_MULTIIPC_PRODUCER
#elif __HW_NVMEDIA_PROJ_MULTIIPC_CONSUMER_CUDA
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_MULTIIPC_CONSUMER_CUDA
#elif __HW_NVMEDIA_PROJ_MULTIIPC_CONSUMER_ENC
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_MULTIIPC_CONSUMER_ENC
#else
#define HW_NVMEDIA_PROJ HW_NVMEDIA_PROJ_IMX728
#endif

#endif
